### ISSUE TITLE
Attempting to create a user using the dynatrace_user resource throws unsupported protocol scheme "" when performed against a cloud tenant

### ISSUE THREAD

**Issue by MarkIannucci** [dynatrace-oss/terraform-provider-dynatrace#123]
This is similar to -- and potentially a duplicate of -- #34.

Today, I attempted to create a user using the following code:

```
resource "dynatrace_user" "dtuser" {
  for_each = {
    for index, user in var.admin_users :
    user.email => user
  }

  email      = each.value.email
  first_name = each.value.first_name
  last_name  = each.value.last_name
  user_name  = each.value.user_name
  groups = [
    "6ac1ee27-0f90-41f1-a044-26357a63f31d"   # Finance Admin
    , "c8ca14c2-853c-4c08-855b-9b60c31c6fb4" # Monitoring viewer
    , "1b1a36cf-7900-4a8e-b4c0-edba5f5bed3d" # Deployment admin
    , "0a67978c-c0bd-43ab-aa78-55728c72e4a7" # Account manager
    , "f589dd8d-1c62-44d3-933b-e262c2bfd0f5" # Log viewer
    , "9ca31a50-fe03-44c5-9166-b1437df3fd67" # Confidential data admin
    , "94ca0118-7fe5-4e04-85ec-c9d2500fee6f" # Monitoring admin
    , "522fab31-0382-4f0d-92d9-ee3f7f3181c4" # Security admin
    , "8ae754c1-f17b-427a-a5bf-5eaf2b5a10d6" # Account viewer
  ]
}
```
with the following variable defined:

```
variable "admin_users" {
  type = list(object({
    email      = string
    first_name = string
    last_name  = string
    user_name  = string
  }))
  description = "Contains the list of admins to create in the APM's account"
  default = [
    {
      email      = "test@test.com"
      first_name = "Testy"
      last_name  = "Tester"
      user_name  = "test@test.com"
      dt_userid = ""
    }
  ]
}
```
And provider

```
terraform {
  required_version = ">= 1.0.0, < 2.0.0"

  required_providers {
    dynatrace = {
      version = "1.10.0"
      source  = "dynatrace-oss/dynatrace"
    }
  }
}

provider "dynatrace" {
  dt_env_url   = var.dt_env_url
  dt_api_token = var.dt_api_token
}
```

Terraform `terraform plan`ned it well.  Unfortunately on apply I received the following error:

```
dynatrace_user.dtuser["test@test.com"]: Creating...
╷
│ Error: Post "/api/v1.0/onpremise/users": unsupported protocol scheme ""
│
│   with dynatrace_user.dtuser["test@test.com"],
│   on dynatrace.tf line 1, in resource "dynatrace_user" "dtuser":
│    1: resource "dynatrace_user" "dtuser" {
│
╵
```

I used real information where the test stuff is written.

**Comment by msmost** [comment]
@MarkIannucci I've run into this same problem. We would like to use the dynatrace_user_group resource but get the same error because we are using a cloud tenant. Seems as though these resources are only setup to work against an on-prem managed cluster. @Dynatrace-Reinhard-Pilz We would love to see the resource expanded to allow for configuration of cloud tenant Account Management API.

**Comment by kishikawa12** [comment]
Hi @MarkIannucci @msmost,

[Release v1.16.0](https://github.com/dynatrace-oss/terraform-provider-dynatrace/releases/tag/v1.16.0) introduced `dynatrace_iam_user` and `dynatrace_iam_group` which allows user and group management for SaaS accounts. In order to use these resources you will first need to configure an OAuth Client. Further details about that can be found within the documentation of both resources. The current implementation does not support configuration of policies, but the plan is to introduce that in the next release.

Regards,
Kodai

**Comment by MarkIannucci** [comment]
Thanks.  Closing.
