### ISSUE TITLE
[Feature] Azure Flexible server supporting

### ISSUE THREAD

**Issue by JayChanggithub** [dynatrace-oss/terraform-provider-dynatrace#141]
I working on Azure services monitoring through dynatrace also do automate setup with Azure monitoring via terraform(This provider). However i go through documentation for setting Azure extra service which Azure PostgresSQL flexible server  in dynatrace service supporting. I couldn't not setup right configuraion in terraform. Have anything advise?

```
resource "dynatrace_azure_credentials"  "azure_resources_monitor" {
    active                       = true
    monitor_only_tagged_entities = true
    app_id                       = var.app_id
    auto_tagging                 = true
    directory_id                 = var.directory_id
    key                          = var.svc_secret
    label                        = var.cluster_of_resource_group

    monitor_only_tag_pairs {
       name                      = var.cluster_of_resource_group
       value                     = "true"
    }

    supporting_services {
        name                     = "cloud:azure:postgresql:server"
    }

   // whether support Flexible DB in here?  
   supporting_services {
        name                     = "cloud:azure:postgresql:flexibleserver"
    }


    supporting_services {
        name                     = "cloud:azure:hdinsight:cluster"
        monitored_metrics {
            dimensions           = [ "MetricName", ]
            name                 = "NumActiveWorkers"
        }
        monitored_metrics {
            dimensions           = [ "HttpStatus", ]
            name                 = "GatewayRequests"
        }
        monitored_metrics {
            dimensions           = [ "HttpStatus", ]
            name                 = "CategorizedGatewayRequests"
        }
    }
}
```

**Comment by JayChanggithub** [comment]
In addition. How to execute `terraform-provider-dynatrace export dynatrace_azure_credentials` when command "terraform-provider-dynatrace " not found in my enviroment?

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello @JayChanggithub ,

When you type in `terraform init` within the directory where your `.tf` files are located it automatically creates a subfolder `.terraform/providers` where it downloads the third party providers to, that are being used within your `.tf` files - including this one (`terraform-provider-dynatrace` on Linux, `terraform-provider-dynatrace.exe` on Windows).
By default Terraform Providers are not meant to get executed directly - the Terraform CLI invokes them under the hoods.
Our provider is special in that regard. Please take a look at this [section of the documentation](https://github.com/dynatrace-oss/terraform-provider-dynatrace#exporting-existing-configuration-from-a-dynatrace-environment) for a few examples.

Yesterday I took a quick look at the schema of the REST API for Azure Credentials - I couldn't identify any properties that are specifically required for Azure Flexible Server Setup.  To me that means, that, if you can configure it via WebUI, you should also be able to configure it via Terraform.
In some cases it is not really easy to find the correct JSON payload for the REST API, that's equivalent to what has been configured via WebUI - and because the Terraform Provider just utilizes the REST API, also here the corrent syntax for certain configurations is difficult to guess. That's the reason why we've developed the `terraform-provider-dynatrace export` functionality. It's meant to be an easy way to get `.tf` files produced for settings that are already configured in an environment.

Makes sense?

**Comment by JayChanggithub** [comment]
Hi @Dynatrace-Reinhard-Pilz,
Thanks for your explaining distinctly. It's look make sense. I  be going to get into take look. Once got anything further outcome. I will feedback soon here.

**Comment by JayChanggithub** [comment]
Hi @Dynatrace-Reinhard-Pilz,
i'd like to inform you to aware it. I be able to enable Flexible service via terraform. The api payload as well as terraform code as below

```
{"configuredServices":[{"serviceShortName":"cloud:azure:postgresql:server","metrics":[{"name":"cpu_percent","dimensions":[]},{"name":"memory_percent","dimensions":[]},{"name":"active_connections","dimensions":[]},{"name":"io_consumption_percent","dimensions":[]},{"name":"connections_failed","dimensions":[]},{"name":"network_bytes_egress","dimensions":[]},{"name":"network_bytes_ingress","dimensions":[]},{"name":"pg_replica_log_delay_in_seconds","dimensions":[]},{"name":"serverlog_storage_percent","dimensions":[]},{"name":"storage_percent","dimensions":[]}]},{"serviceShortName":"cloud:azure:hdinsight:cluster","metrics":[{"name":"NumActiveWorkers","dimensions":["MetricName"]},{"name":"GatewayRequests","dimensions":["HttpStatus"]}]},{"serviceShortName":"cloud:azure:postgresql:flexibleservers","metrics":[]}]}
```

```
resource "dynatrace_azure_credentials"  "azure_resources_monitor" {
    active                       = true
    monitor_only_tagged_entities = true
    app_id                       = var.app_id
    auto_tagging                 = true
    directory_id                 = var.directory_id
    key                          = var.svc_secret
    label                        = var.cluster_of_resource_group

    monitor_only_tag_pairs {
       name                      = var.cluster_of_resource_group
       value                     = "true"
    }

    supporting_services {
        name                     = "cloud:azure:postgresql:server"
    }

   # added this line
    supporting_services {
        name                     = "cloud:azure:postgresql:flexibleservers"
    }

    supporting_services {
        name                     = "cloud:azure:hdinsight:cluster"
        monitored_metrics {
            dimensions           = [ "MetricName", ]
            name                 = "NumActiveWorkers"
        }
        monitored_metrics {
            dimensions           = [ "HttpStatus", ]
            name                 = "GatewayRequests"
        }
        monitored_metrics {
            dimensions           = [ "HttpStatus", ]
            name                 = "CategorizedGatewayRequests"
        }
    }
}
```

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Thank you for the final feedback. If you have further questions on this topic, feel free to re-open.
