### ISSUE TITLE
feature request: policy management via Terraform

### ISSUE THREAD

**Issue by ggreen05** [dynatrace-oss/terraform-provider-dynatrace#158]
**Is your feature request related to a problem? Please describe.**
I'd like to manage our account settings completely via IaC and there are some features missing.

**Describe the solution you'd like**
I'd like the Policy management API available as resources and data sources https://www.dynatrace.com/support/help/dynatrace-api/account-management-api/policy-management-api/policies/post-policy 

**Describe alternatives you've considered**
N/A

-----------
I can currently create groups via Terraform, this is awesome but sometimes I have policies that I like to assign to groups so I'd love the ability to create policies via Terraform.

Love all the effort that is being put towards this provider, really appreciate it from down here in New Zealand 💯

**Comment by mbrunn** [comment]
@Dynatrace-Reinhard-Pilz
Is this planned?

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello @mbrunn 
Yes, it is planned. I need to ask for another couple of weeks of patience, though. Our focus is currently on getting as many resources based on Settings 2.0 done.

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello everyone,

The next release will contain the resources `dynatrace_iam_policy` and `dynatrace_iam_policy_binding`.

I'd appreciate it if you would take look at the documentation templates for [dynatrace_iam_policy](https://github.com/dynatrace-oss/terraform-provider-dynatrace/blob/main/templates/resources/iam_policy.tmpl) and [dynatrace_iam_policy_binding](https://github.com/dynatrace-oss/terraform-provider-dynatrace/blob/main/templates/resources/iam_policy_bindings.tmpl) upfront in order to see how they are expected to be used.

The API endpoints for these two resources were everything but straightforward to be transformed into Terraform resources, that's why it doesn't hurt to get some feedback before they go online next week.

best regards,
Reinhard

**Comment by mbrunn** [comment]
Hello Reinhard,
this looks great. Thank you for the work you put in to make this possible. I think this will help tremendously with implementing large scale iam-policies.

Any future plans to implement the same for managed installations, since you already put the work in to make it possible for SaaS? As far as I was able to see, the endpoints between SaaS and managed seem to be really close. ("iam/**_v1_**/repo" vs "iam/repo")

KR
Michael

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hi Michael,
You're right, I expect the counterpart for managed clusters to be very similar. Payloads and endpoints are literally the same. I just didn't want to promise them for the upcoming release. The release after is more likely.
