### ISSUE TITLE
Cannot create user and group via terraform (dynatrace saas)

### ISSUE THREAD

**Issue by mkhatiri** [dynatrace-oss/terraform-provider-dynatrace#161]
**Describe the bug**
I cannot create a user group via terraform (we are in saas solution)

**Code**

resource "dynatrace_user_group" "dopt_mz_group" {
    name = "dopt_prod"
}

**ERROR**

╷
│ Error: Post "/api/v1.0/onpremise/groups": unsupported protocol scheme ""
│
│   with dynatrace_user_group.group1,
│   on main.tf line 66, in resource "dynatrace_user_group" "group1":
│   66: resource "dynatrace_user_group" "group1" {
│
╵

**Comment by rpionke** [comment]
@mkhatiri The "dynatrace_user_group" resource is only available for managed installations

**Comment by iuliancristea** [comment]
Is there a plan for adding in support for account-wide management in the provider?

**Comment by kishikawa12** [comment]
Hi @mkhatiri @iuliancristea,

[Release v1.16.0](https://github.com/dynatrace-oss/terraform-provider-dynatrace/releases/tag/v1.16.0) introduced `dynatrace_iam_user` and `dynatrace_iam_group` which allows user and group management for SaaS accounts. In order to use these resources you will first need to configure an OAuth Client. Further details about that can be found within the documentation of both resources. The current implementation does not support configuration of policies, but the plan is to introduce that in the next release.

Regards,
Kodai

**Comment by mkhatiri** [comment]
Hi @kishikawa12,

Thank you for your information.

I test it but I got this error :

│ Error: Incorrect Authorization header in request - expected `Bearer`!
│
│   with dynatrace_iam_user.med,
│   on users.tf line 7, in resource "dynatrace_iam_user" "med":
│    7: resource "dynatrace_iam_user" "med" {
│

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello @mkhatiri , with the upcoming release it will be possible to specify the accountID with and without the `urn:dtaccount:` prefix, hence there won't be any confusion anymore.
