### ISSUE TITLE
Tagging dynatrace_web_application (Resource)

### ISSUE THREAD

**Issue by yasin-amadmia-mck** [dynatrace-oss/terraform-provider-dynatrace#217]
**Describe the bug**
There seems to be no way of tagging `dynatrace_web_application` Resource. These are Dynatrace Tags that are used within the Dynatrace Managament Zone rules. The `user_tags` are available but are for RUM. For example https://registry.terraform.io/providers/dynatrace-oss/dynatrace/latest/docs/resources/browser_monitor#tags

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello @yasin-amadmia-mck and @dmytro-malovany,

Your observation is correct - when it comes to tagging the REST API of Dynatrace is a bit inconsistent. Some resources allow for specifying the tags of the resource, some don't.

In order to tag a Web Application you can utilize the resource `dynatrace_custom_tags`, like in this example:
```
resource "dynatrace_custom_tags" "application_custom_tags" {
  entity_selector = "entityId(\"APPLICATION-################\")"
  tags {
    filter {
      context = "CONTEXTLESS"
      key     = "KeyA"
      value   = "ValueA"
    }
  }
}
```
Using the [Entity Selector](https://www.dynatrace.com/support/help/dynatrace-api/environment-api/entity-v2/entity-selector) here, you can essentially target any kind of resource.

best regards,
Reinhard
