### ISSUE TITLE
Terraform examples for each resource

### ISSUE THREAD

**Issue by Satak** [dynatrace-oss/terraform-provider-dynatrace#23]
Currently documentation for each resource type is fine but there isn't any terraform examples. It's very nice to have exact terraform example for each resource type so it's fast and easy to take into use. Take a look for example Azure provider documentation <https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/virtual_machine>.

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Agreed, a couple of examples will be required as part of the documentation sooner or later. Right now we're translating based on the documentation of the Configuration REST API of the Dynatrace Server - which is at the moment our only source.

In order to alleviate that to a certain extent we've provided the ability to launch the executable `terraform-provider-dynatrace` directly (and not just as a plugin for the terraform cli).
Executing `terraform-provider-dynatrace download <API_URL> <API_TOKEN>` essentially downloads the current settings onto you local machine and automatically creates the `.tf` files. In some cases (e.g. for Dashboards, where the configuration settings are usually pretty complex) that's even a better approach, since you usually are will be creating them using the WebUI anyways.

That's of course no excuse to not provide samples for ANY configuration settings (e.g. Alerting Profiles, Management Zones, ...). We will invest the time for these use cases in the future.
