### ISSUE TITLE
dynatrace_web_application: Tag with UniqueId 1 was deleted before

### ISSUE THREAD

**Issue by mattBaumBeneva** [dynatrace-oss/terraform-provider-dynatrace#246]
**Describe the bug**
We are attempting to add User Tagging to our Web Applications, as shown in the examples from this project.
We are obtaining the following error from applications that have already had User Tag rules defined and removed in the past:
**Tag with UniqueId 1 was deleted before**
This seems to be due to the fact that Dynatrace auto-increments user_tags.tag.id, and an existing ID can never be reused once a rule has been deleted.
This feature is unusable if we have to manually manage tag IDs for each application, which are an implementation detail.

**To Reproduce**
1. Manually define an initial User Tag rule on an application (it will have id = 1)
2. Delete the User Tag rule
3. Attempt to apply a User Tag rule to the application with Terraform:
```
user_tags {
  tag {
	cleanup_rule = "cleanup rule here"
	id           = 1
	ignore_case  = false
	metadata_id  = 1
  }
 }
}
```

**Expected behavior**
The user tag is applied with the lowest ID number allowed by Dynatrace.

**Additional context**

- Terraform 1.0.8
- Dynatrace provider 1.28.0
- Adding the ID to ignore_changes has no effect on the problem

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello Matt,

What you've stumbled across is a limitation that exists for all clients of the Dynatrace REST API. The details are a bit complicated, but in order to maintain a history of Visits, it is not allowed to re-use these unique IDs. Also our team was not aware of that fact until you filed the issue.

With the upcoming release, in order to deal with these restrictions properly, the property `id` won't be taken into consideration anymore. The attribute is still available within the Schema, in order to stay backwards compatible. But the Provider won't consider its value anymore. The provider will maintain a computed attribute `unique_id` - and it will determine it's value autonomously. 

best regards,
Reinhard

**Comment by mattBaumBeneva** [comment]
That sounds perfect. Can you tell me when the release with this fix will be published?

**Comment by Dynatrace-Reinhard-Pilz** [comment]
We usually push out updates once per week. So, mid next week either v1.30.2 (if the release just contains bug fixes) or v1.31.0 (if it contains new functionality) will contain the fix.

**Comment by mattBaumBeneva** [comment]
Thank you.

**Comment by mattBaumBeneva** [comment]
I can confirm that this issue is resolved.
