### ISSUE TITLE
dynatrace_slo_v2 return data unusable

### ISSUE THREAD

**Issue by paulmorar** [dynatrace-oss/terraform-provider-dynatrace#249]
**Describe the bug**
dynatrace_slo_v2 returns an incorrect id. Whenever you need to use the id in the context of another resource, such as dashboards, it expects that you pass in a uuid, while the resource creation returns something non-standard.

This can be bypassed by using data sources, but it is suboptimal.

**To Reproduce**
1. Create an SLO using V2
2. Check the output
3. Create an SLO using V1
4. Check the output

**Expected behavior**
The id result should be the same and usable together with other resource components.

**Screenshots**
![image](https://github.com/dynatrace-oss/terraform-provider-dynatrace/assets/12514384/742378cc-b2b0-469f-9dd3-8e9ba5e11eac)

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello Paul, you're absolutely correct here. We neglected to introduce the attribute `legacy_id` for the resource `dynatrace_slo_v2`. This is how we've dealt with the same situation for other resources (`dynatrace_management_zone_v2`, `dynatrace_alerting`, ...).

A bit of background here:
Resources with the `_v2` suffix are in almost all cases related to the [Settings 2.0 API](https://www.dynatrace.com/support/help/dynatrace-api/environment-api/settings) - as opposed to the [Configuration API](https://www.dynatrace.com/support/help/dynatrace-api/configuration-api) or the [Environment API](https://www.dynatrace.com/support/help/dynatrace-api/environment-api).
Several endpoints for the Configuration/Environment API have meanwhile gotten deprecated by Dynatrace - in order to favor their alternative endpoints within the Settings 2.0 API.

What has turned out very inconvenient is, that Settings 2.0 produces different IDs for configuration settings than the old gen REST API endpoints. Even worse, sometimes you need to refer to the Settings 2.0 ID, sometimes you need to refer to the UUID, depending on which resource contains the reference.

That's what the attribute `legacy_id` is meant for. It is possible to decode the UUID from any Settings 2.0 ID, and the Terraform Provider does that automatically for you. Again, for `dynatrace_slo_v2` we forgot to introduce that attribute.

With the upcoming release you will be able to use `dynatrace_slo_v2.<resourcename>.legacy_id`.

**Comment by paulmorar** [comment]
Big thanks for the explanation @Dynatrace-Reinhard-Pilz 

I am thinking whether it would make sense to set up an online session with you on giving us a tour of the repo structure - perhaps we could contribute ourselves a bit more constructively rather than opening an issue 🙂

**Comment by Dynatrace-Reinhard-Pilz** [comment]
We've done that with other community members in the past already. If you're really interested, please reach out to me via email at reinhard.pilz@dynatrace.com. I'm happy to schedule a Zoom session where we can explain the good, the bad and the ugly of our project.
