### ISSUE TITLE
dynatrace_alerting_profile updates on subsequent runs

### ISSUE THREAD

**Issue by JosephHobbs** [dynatrace-oss/terraform-provider-dynatrace#26]
When upgrading to v1.0.10 I found that Terraform is identifying modifications required on subsequent runs for alerting profiles.  I see two specific situations at this point.

- mz_id is updated to an ID (was previously name).
- unknowns is being dropped.
- rules are being recreated due to an order change?

Output attached from init, plan/apply and subsequent apply...

[dynatrace_alerting_profile-logs.txt](https://github.com/dynatrace-oss/terraform-provider-dynatrace/files/6454396/dynatrace_alerting_profile-logs.txt)

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hi Joseph,

The mz_id/unknowns issue definitely looks like a bug. I'm hoping to push out a release that takes care of it by tomorrow.

The root cause for the issue with the apparent necessity for recreating the rules originates from the unfortunate fact, that the order these rules are being delivered by the Dynatrace REST API is not guaranteed - while terraform expects this order to be consistent.
In order to mitigate that (since it actually has led to sporadic test failures in the past), the terraform provider since v1.0.10 guarantees a predictable order. Your `.tf` files were likely being produced by a provider version older than v1.0.10. Am I right?

There ARE ways to teach terraform to not care about the order of sub-resources, but this comes with the tradeoff, that terraform no longer validates the contents of these rules explicitly. Hence I decided against it.

Eventually you already have figured out that just bringing the rules into the predictable order takes care of this situation.

Let me know if you have further questions.

**Comment by JosephHobbs** [comment]
Makes sense on the ordering issue.  I've seem similar behavior with other providers and can understand the challenges there.

Thanks!

**Comment by Dynatrace-Reinhard-Pilz** [comment]
[v1.0.11](https://github.com/dynatrace-oss/terraform-provider-dynatrace/releases/tag/v1.0.11) takes care fo the issue with the attributes `mz_id` and `unknowns`.

**Comment by JosephHobbs** [comment]
looks good.  thank you!
