### ISSUE TITLE
400 error returned when creating data.dynatrace_entity

### ISSUE THREAD

**Issue by TheLooostOne** [dynatrace-oss/terraform-provider-dynatrace#281]
**Describe the bug**
We would like to create a new data.dynatrace_entity. 
`data "dynatrace_entity" "component" {
  type = "SERVICE"
  name = "@component/xyz"
}`

But this input gives `Error: status code 400 (expected: [200]): <!doctype html><html lang="en"><head><title>HTTP Status 400 – Bad Request</title><style type="text/css">body {font-family:Tahoma,Arial,sans-serif;} h1, h2, h3, b {color:white;background-color:#525D76;} h1 {font-size:22px;} h2 {font-size:16px;} h3 {font-size:14px;} p {font-size:12px;} a {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 400 – Bad Request</h1></body></html>`
 When calling the Dynatrace API manually everything works as expected.
Provider version : 1.30.0

**To Reproduce**
1. Create a new tf file containing the previous input
2. Apply terraform

**Expected behavior**
200 code should be returned 

**Desktop (please complete the following information):**
- OS: Windows 10 Enterprise
- Browser : chrome
- Version : 21H2

**Comment by TheLooostOne** [comment]
Hi,
Thank you for the quick response. I see that in the err.log file we get :
`2023/06/21 18:03:14 GET https://[...]/api/v2/entities?pageSize=4000&entitySelector=type("SERVICE")&fields=tags
2023/06/21 18:03:14    400 <!doctype html><html lang="en"><head><title>HTTP Status 400 – Bad Request</title><style type="text/css">body {font-family:Tahoma,Arial,sans-serif;} h1, h2, h3, b {color:white;background-color:#525D76;} h1 {font-size:22px;} h2 {font-size:16px;} h3 {font-size:14px;} p {font-size:12px;} a {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 400 – Bad Request</h1></body></html>
`
Same error occurs when upgrading the version unfortunately.

**Comment by Dynatrace-Reinhard-Pilz** [comment]
@TheLooostOne, that specific response is not coming from the Dynatrace REST API. Is it possible that an Apache based proxy server is sitting in between the host that runs Terraform and the Dynatrace Cluster? The CSS code within the response makes me thing so, simply because of the formatting.

The next release of the provider will contain a small change when it comes to url encoding the parameter `entitySelector`.
But you can as a matter of fact test this out right now with v1.33.0. Instead of this syntax
```
data "dynatrace_entity" "component" {
  type = "SERVICE"
  name = "@component/xyz"
}
```
just use the `entity_selector` attribute.
```
data "dynatrace_entity" "component" {
  entity_selector = "type(SERVICE),entityName.equals(@component/xyz)"
}
```
In that case the request would already look slightly different.
Are you getting different results here?

**Comment by antonochel** [comment]
@Dynatrace-Reinhard-Pilz Thank you for this suggestion, this solved our problem :)

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Please leave a message in case there are open question, and we'll re-open the ticket.
