### ISSUE TITLE
Terraform apply occasionally hangs on Web Applications

### ISSUE THREAD

**Issue by mattBaumBeneva** [dynatrace-oss/terraform-provider-dynatrace#283]
**Describe the bug**
This issue only started occuring recently. When running Terraform Apply in our pipeline, the job occasionally hangs on certain Web Applications. The applications in question are in production and receiving RUM data.

We observe that:
1. The Web Application is modified, event though we made no changes to its Terraform configuration
2. The changes are actually applied in Dynatrace, which we can confirm via the Web interface
3. The apply step hangs forever and must be manually aborted (we have let it run for more than one hour)

**To Reproduce**
1. Run Terraform Apply on Web Applications in production
4. The apply job hangs

**Expected behavior**
Terraform applies Web Application configurations in a limited amount of time.

**Screenshots**
<img width="743" alt="image" src="https://github.com/dynatrace-oss/terraform-provider-dynatrace/assets/127420012/6e58fc35-f49f-4f4d-b030-90ce33f5dc56">

**Additional context**
Dynatrace provider version: 1.33.0
Terraform version: 1.0.8

**Comment by mattBaumBeneva** [comment]
I don't know if this could be the cause of the behavior, but the property we most recently started configuring on our Apps is:
"monitoring_data_path"

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello @mattBaumBeneva,
Sorry for the late response here. We DID introduce a few changes (coincidentally regarding diffs) for `dynatrace_web_application`. The fact that you're coming in with this issue looks therefore very suspicious.

For further diagnosis please set the environment variables
```
DYNATRACE_LOG_HTTP=terraform-provider-dynatrace.http.log
DYNATRACE_HTTP_RESPONSE=true
```
When set the provider will dump out HTTP traffic to the files `terraform-provider-dynatrace.http.log` and `terraform-provider-dynatrace.http.err.log`.

I would suggest to send the log output to terraform@dynatrace.com instead of pasting it here on the ticket. Web application can contain all sorts of sensitive information - a public GitHub post is the wrong place for that.

**Comment by mattBaumBeneva** [comment]
We haven't reproduced the issue in recent days, but if we do, I'll try those steps. Thanks.

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Thanks for the info @mattBaumBeneva. I will close the ticket until further notice. In case the issue re-emerges, drop us a message and I will reopen.
