### ISSUE TITLE
dynatrace_aws_credentials missing external ID

### ISSUE THREAD

**Issue by agentreno** [dynatrace-oss/terraform-provider-dynatrace#287]
**Describe the bug**

The `external_id` field in `authentication_data` block is set to an empty string after a `dynatrace_aws_credentials` resource is created. Checking the Dynatrace UI shows that there is such a value not reflected in terraform state.

The documentation for this resource and also a [previous github issue](https://github.com/dynatrace-oss/terraform-provider-dynatrace/issues/200#issuecomment-1433231654) makes me think this might be intentional rather than a bug, but I'm not sure why, and it complicates full terraform automation that includes an IAM role with a trust policy that uses this external ID as a condition. 

**To Reproduce**

1. Create a `dynatrace_aws_credentials` resource with an authentication data block referencing an account ID and IAM role.
2. Pass the resource's external ID attribute to another resource (IAM role trust policy in my case, but any will do, even output).
3. `terraform refresh` and `terraform show -json` confirms the absence of the value over time.

**Expected behavior**

The external ID field should be populated, even if it is generated once per tenant and even if it is sensitive, to allow other resources to use it.

**Desktop (please complete the following information):**
 - OS: Ubuntu Linux

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello @agentreno,

You're right, the behavior here is a bit unpredictable. I've done a couple of experiments - using the REST API directly.
It looks like that this attribute is getting populated automatically but with a non-negligible delay. During my local tests it took up to a minute until the `externalId` was available.

What I *can* do is to introduce additional polling after a resource `dynatrace_aws_credentials` has been created - needless to say, that will have consequences regarding performance. Creating such a resource may then take up to a minute until it's safe to say that the `externalId` is available.

What's available right now, is of course the data source `dynatrace_aws_iam_external`. The configuration
```
data "dynatrace_aws_iam_external" "aws_external" {
}
```
allows you to access the external id from anywhere via `${data.dynatrace_aws_iam_external.id}`. 

Finally, I can also imagine a combination of the two alternatives mentioned above. Instead of *polling* until the field has gotten populated by the Dynatrace Server, we could simply execute an additional REST call after creating an `dynatrace_aws_credentials` setting and populate the field manually. After all, it's an ID that is not supposed to change.

Your thoughts?

**Comment by agentreno** [comment]
Thanks for looking into it @Dynatrace-Reinhard-Pilz much appreciated as always.

I don't want to speak for everyone but my view is that a dynatrace_aws_credentials object isn't fully created until it's external ID is also populated, and it should poll until then. I can only imagine a ~60 second delay being undesirable for people who don't want to use that value - but then how are they creating their IAM role trust policies? I don't think you should cater for a half-IaC approach like that when the delay isn't that long, many other terraform providers take longer to create some resources.

If you take this approach, as a user of the provider, I won't have to do anything unintuitive like use an additional data resource, just create dynatrace_aws_credentials as normal, reference it in IAM role trust policy, and wait a bit longer for everything to be created and function as expected.

What do you think?

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Your response is exactly why I asked about your opinion. Our team is developing the provider, but isn't utilizing it productively. For that reason it pays off to listen to people who are actually using it.

... and yes, your reasoning makes sense, the credentials aren't *fully* available unless the attribute is available, and pretending otherwise tends to backfire.
In addition to the polling mechanism we nevertheless will have to introduce a fallback, that utilizes the response from the endpoint `/api/config/v1/aws/iamExternalId`. I'm thinking here about occasionally very busy Dynatrace clusters, where the estimated 60 seconds simply aren't enough. Something like that isn't the norm, but we've seen that with other resources like synthetic monitors. It's essentially a safety net, and avoids running into an endless loop.

The changes should make it into the next release - I will keep the ticket open until the actual commit has happened.

Thanks for you input, much appreciated.
