### ISSUE TITLE
Importing Dynatrace SLO Resource by ID

### ISSUE THREAD

**Issue by omar25h** [dynatrace-oss/terraform-provider-dynatrace#288]
I am trying to import an existing SLO (v1) into TF state via `terraform import`. I have the SLO ID as a UUID. When trying to import it to the terraform state it fails, complaining that it **Cannot import non-existent remote object**

the command tried looks like `terraform import dynatrace_slo.service-availability-slo d8dae3c7-0dba-435d-9f1c-d31b069c4b0b` where `dynatrace_slo.service-availability-slo` is the resource I am trying to import the SLO into (it has the same name). I am not sure whether the SLO ID supplied is sufficient to do the import or some prefix/suffix to the ID is needed

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello @omar25h,

Your command looks very ok. I just tried with one of my SLOs successfully. Here are the steps I took:

First, I added an empty resource block to one of the .tf files in my module.
```
resource "dynatrace_slo" "service-availability-slo" {
}
```

Then I executed `terraform import dynatrace_slo.service-availability-slo 17ca4a95-7762-34be-97ef-cfc9a2327061`. The UUID is obviously different than in your case. 
At this point you need to be aware of the fact, that the API Token you've configured via environment variable `DYNATRACE_API_TOKEN` or via provider attribute `dt_api_token` needs to include the scope `Read SLO` (and later on, when you want to make changes to the resource also the scope `Write SLO`). 
A successful execution of `terraform import` produces this output:
```
dynatrace_slo.service-availability-slo: Importing from ID "17ca4a95-7762-34be-97ef-cfc9a2327061"...
dynatrace_slo.service-availability-slo: Import prepared!
  Prepared dynatrace_slo for import
dynatrace_slo.service-availability-slo: Refreshing state... [id=17ca4a95-7762-34be-97ef-cfc9a2327061]

Import successful!

The resources that were imported are shown above. These resources are now in
your Terraform state and will henceforth be managed by Terraform.
```
At this point the configuration of the SLO is, of course, only stored within your `terraform.tfstate` file. But the empty resource block you've created in step 1 doesn't match up with that, yet.
Therefore, as a next step, you need to execute `terraform show`. That will produce HCL code for everything that's currently stored within the state file. One of the blocks in the output should look like this:
```
# dynatrace_slo.service-availability-slo:
resource "dynatrace_slo" "service-availability-slo" {
    evaluation        = "AGGREGATE"
    id                = "17ca4a95-7762-34be-97ef-cfc9a2327061"
    metric_expression = "(100)*((calc:service.slo_aiapi_notfailedrequestcount:splitBy())/(calc:service.slo_aiapi_allrequestcount:splitBy()))"
    name              = "New SLO"
    target            = 99.98
    timeframe         = "-1w"
    warning           = 99.99
}
```
Finally, you can copy&paste that resource block and replace the empty block from the beginning with it.
Be sure to remove the `id` attribute. Terraform doesn't allow users to specify the `id` explicitly, because Terraform determines that value.

At this point your configuration (within the .tf files) will be in sync with the configuration of the SLO in your Dynatrace environment. Therefore, when you execute `terraform plan`, the output should look like this, essentially confirming that you're in sync.
```
dynatrace_slo.service-availability-slo: Refreshing state... [id=17ca4a95-7762-34be-97ef-cfc9a2327061]

No changes. Your infrastructure matches the configuration.

Terraform has compared your real infrastructure against your configuration and found no differences, so no changes are needed.
```

Let me know if that helps,
Reinhard

**Comment by omar25h** [comment]
This does help, thanks Reinhard!  😄
