### ISSUE TITLE
Bukcet creation through terraform

### ISSUE THREAD

**Issue by shobhaagarwal** [dynatrace-oss/terraform-provider-dynatrace#301]
IN Dynatrace UI we were able to create bucket with the help of swagger API in Bucket Management. Could I get some context about how we can automate it with the help of terraform. 
We could not see any Resource block for that. Is that going to be release in further provider version of terraform?

Thanks,
Shobha

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello @shobhaagarwal,
We're currently in the early stages for implementing resources for the Platform REST APIs. The first batch of resources will focus on  Automation (Workflows, ...). Bucket Definitions are pretty high on our list, because it's fairly straightforward endpoint.

I cannot give you a fixed ETA for when it will be available, but you can expect something in September.
