### ISSUE TITLE
Associate Dynatrace source policies e.g "AppEngine - User" with group in Terraform

### ISSUE THREAD

**Issue by jsoellner** [dynatrace-oss/terraform-provider-dynatrace#313]
**Is your feature request related to a problem? Please describe.**
We are in the process of switching to IAM polices instead of permissions and I want to manage these in Terraform, using our standard GitOps approach to Dynatrace configuration management.

Currently, I can create a "dynatrace_iam_policy_bindings" resource to associate a policy that I have created in Terraform, with a group I have created in Terraform - that works no problem.

But when I try to associate a pre-existing Dynatrace-created policy, it fails with the error:
"Error: The policy  is defined for  = . It cannot be used within the scope environment = xxxxxxx". I get a similar error when I try an account level binding as well.

The only solution for complete policy management currently is for us to recreate all of the pre-existing policies. It would be great to have the ability to associate a pre-existing Dynatrace-created policy with a group.

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello @jsoellner, if it's possible to work around that problem using the REST API, we will look into it. Need to ask for a bit more patience, though.

**Comment by kishikawa12** [comment]
Hi @jsoellner,

We appreciate your patience. The reason why you were running into those issues is because the resource ID and other IDs referenced in the configuration had a specific format for IAM policy and policy bindings. The update released today v1.48.0 includes an enhancement to the export utility to retrieve existing `dynatrace_iam_policy` and `dynatrace_iam_policy_bindings` configuration.

Example command:
`terraform-provider-dynatrace -export -ref -id dynatrace_iam_policy dynatrace_iam_policy_bindings`

This should allow you to retrieve and manage existing policies and policy bindings by using `terraform import` or the `-import-state` flag available via the export utility. I hope that helps!
