### ISSUE TITLE
The specified key is not applicable to the specified attribute.

### ISSUE THREAD

**Issue by ARZ-SagA** [dynatrace-oss/terraform-provider-dynatrace#32]
Hi,

I downloaded a MMZ and wanted to apply it but I got the following error:

```
Error: {
  "code": 400,
  "message": "Constraints violated.",
  "constraintViolations": [
    {
      "parameterLocation": "PAYLOAD_BODY",
      "location": "",
      "message": "The specified key is not applicable to the specified attribute. Please use the key for the discriminator 'STRING' for the attribute 'CLOUD_APPLICATION_NAMESPACE_LABELS'.",
      "path": "rules[3].conditions[0].key.attribute"
    }
  ]
}
```
This is the rule which is referenced in the error
```
  rules {
    enabled = true
    type = "CLOUD_APPLICATION"
    conditions {
      string {
        case_sensitive = false
        value = "(?>ed220|bs290)"
        negate = false
        operator = "REGEX_MATCHES"
      }
      string_key {
        attribute = "CLOUD_APPLICATION_NAMESPACE_LABELS"
	dynamic_key = "arz.at/organisation-unit"
      }
    }
  }
```

If i add "unkowns" to the string_key i get this message:
Error: invalid character 'C' looking for beginning of value

```
    string_key {
      attribute = "CLOUD_APPLICATION_NAMESPACE_LABELS"
unknowns = "CLOUD_APPLICATION_NAMESPACE_LABELS"
dynamic_key = "arz.at/organisation-unit"
    }
```

Am I using the unkonwns wrong?

**Comment by Dynatrace-Reinhard-Pilz** [comment]
I'm afraid you've discovered a bug here. When translating the `string_key` block into JSON the provider failed to pass along the `type` attribute. I've just released [v1.0.15](https://github.com/dynatrace-oss/terraform-provider-dynatrace/releases/tag/v1.0.15) containing  a fix for that.

Regarding the `unknowns` attribute: Purpose of that attribute is to make the terraform provider future proof. In other words, even if the Dynatrace REST API has gotten extended (with several additional properties and attributes) the terraform provider will be able to handle them. Every property offered in JSON format by the REST API that is not part of the HCL Schema for a specific resource will remain encoded within the `unknowns` attribute.
In general you would stumble across them if you're using `terraform-provider-dynatrace download` in order to generate `.tf` files for existing configuration settings (our when importing them using `terraform import`). But on a daily basis you shouldn't be required to actively use that attribute. Any additional properties within `unknowns` would be optional ones.
