### ISSUE TITLE
dynatrace_email_notification keep showing that the profile id need to be changed

### ISSUE THREAD

**Issue by OliviaHY** [dynatrace-oss/terraform-provider-dynatrace#331]
**Describe the bug**
For both dynatrace_email_notification and dynatrace_webhook_notification, after a dynatrace_alerting_profile created in the same terraform config and its ID referred in the notification resource, nothing else change at the second run but terraform output is showing update in the profile ID.
Terraform provider version 1.34.0 and 1.42.0

**To Reproduce**
1. Create a terraform config dynatrace_alerting_profile and a dynatrace_email_notification or dynatrace_webhook_notification with the profile referred.
2. Run tf apply
3. Run tf plan and seeing the profile id need to be updated.

**Expected behavior**

Should be no change when running 3.

**Screenshots**
<img width="1267" alt="image" src="https://github.com/dynatrace-oss/terraform-provider-dynatrace/assets/8557703/9a77ac40-2a77-420e-9521-2569ccee91fd">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser NA

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello @OliviaHY,

I would recommend to use the resource [dynatrace_alerting](https://registry.terraform.io/providers/dynatrace-oss/dynatrace/latest/docs/resources/alerting) instead of [dynatrace_alerting_profile](https://registry.terraform.io/providers/dynatrace-oss/dynatrace/latest/docs/resources/alerting_profile). That will take care of the non-empty plan.

A bit of background information for why this is happening:

The Dynatrace REST API allows for managing Alerting Profiles via two different endpoints. Although you're configuring the same kind of settings with both REST endpoints, they are generating a different `id` for the resource.
The resources `dynatrace_email_notification`, `dynatrace_webhook_notification`, etc. enforce the `id` attribute like it is getting generated for [dynatrace_alerting](https://registry.terraform.io/providers/dynatrace-oss/dynatrace/latest/docs/resources/alerting). It's even a bit more complicated, but bottom line is: during refresh you're only getting the `id` in that format.

In order to offer a way to circumvent this unfortunate limitation of the REST APIs the Terraform Provider offers two sets of resources.
* If you would like to work with the resource [dynatrace_alerting_profile](https://registry.terraform.io/providers/dynatrace-oss/dynatrace/latest/docs/resources/alerting_profile) then you should use the resource [dynatrace_notification](https://registry.terraform.io/providers/dynatrace-oss/dynatrace/latest/docs/resources/notification) for configuring email notifications, web hooks, etc. They are fully compatible regarding the `id` of the Alerting Profile. These resources **are** deprecated, though. The API endpoints they are targeting may not offer the full functionality.
* The resource `dynatrace_alerting` goes along well with every other resource. It offers both kinds of IDs mentioned above - the attribute [id](https://registry.terraform.io/providers/dynatrace-oss/dynatrace/latest/docs/resources/alerting#id) and the attribute [legacy_id](https://registry.terraform.io/providers/dynatrace-oss/dynatrace/latest/docs/resources/alerting#legacy_id).

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Drop us a message, in case there are further questions and we will re-open this ticket.

**Comment by OliviaHY** [comment]
Thank you for the solution and more importantly the whys. I changed the resources and everything is behaving as you said.
