### ISSUE TITLE
Export filter - filter all exported ressources by name, tag or management zone

### ISSUE THREAD

**Issue by SebastianWilhelm** [dynatrace-oss/terraform-provider-dynatrace#332]
We have a lot of management zones in our Dynatrace cluster. When we use the Terrafrom provider to export the ressources, we always get a huge amount of ressources.

It would be great to have a possibility to export all ressources, that belong to a management zone, have a specific tag or substring in the name. I'd like to add this filter as a property to the exporter feature.

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello @SebastianWilhelm,

I'd like to know a bit more about your use case here.
* Are you usually using the `-ref` argument, so you're also getting resources downloaded that are referenced?
* Let's assume you've applied a filter that only downloads resources that belong to a specific management zone. For the resource `dynatrace_email_notification`
  * Would you expect to get **all** of them because that resource doesn't directly depend on management zones
  * Or would you expect to get only the email notifications that depend on Alerting Profiles that belong to the specified management zone
* When filtering by tags, would resources that cannot have tags be excluded?

Would like to clarify your expectations here before starting to implement something that eventually won't fit your use cases.

**Comment by SebastianWilhelm** [comment]
Thanks for the fast reply, @Dynatrace-Reinhard-Pilz 

Here are my answers. I hope that helps. 

- Yes, we use usually the -ref argument to download all references resources.
- When I set a filter, I expect a filtered output. But I understand you concern. I would log a hint to the user, if you want to avoid confusions. 
- Last point is hard to answer: if Idon't know, which resources can't be tagged, I might miss something in my TF scripts. What about downloading all resources, but in a seperate directory (e.g. 'untagged resources'), like you do it for resources, that require attention?
