### ISSUE TITLE
dynatrace_entity returns old APPLICATION_METHOD that is not subscribed

### ISSUE THREAD

**Issue by mattBaumBeneva** [dynatrace-oss/terraform-provider-dynatrace#338]
**Describe the bug**
We have a module that queries Key User Actions in order to perform further configuration (Apdex and SLOs).
On Web Applications that have had KUAs removed and added back in the past, we observe that the following code:

```
data "dynatrace_entity" "kua_with_apdex" {
  count           = length(local.kua_with_apdex)
  entity_selector = "type(\"APPLICATION_METHOD\"),entityName(\"${local.kua_with_apdex[count.index].nom}\"),fromRelationships.isApplicationMethodOf(entityId(\"${dynatrace_web_application.application.id}\"))"
}
```

Will return invalid (old) KUAs. Terraform Apply then returns an error when attempting to define the Apdex for this Method:

`Error: User action is not subscribed: APPLICATION_METHOD-098D3F4F2C21FAE6`

**Steps to reproduce**

1. Manually add a KUA to a Web application
2. Remove the KUA
3. Allow some time to elapse
4. Configure a KUA on the Web App with Terraform
5. Query APPLICATION_METHOD on the App as shown above

**Expected behavior**
Only configuration elements that are still valid should be returned by dynatrace_entity and dynatrace_entities data sources.

**Comment by mattBaumBeneva** [comment]
The current, valid KUA is like so:

```
{
  "entityId": "APPLICATION_METHOD-9D331E070782C327",
  "type": "APPLICATION_METHOD",
  "displayName": "loading of page /clic-webapp/clic",
  "firstSeenTms": 1677267505737,
  "lastSeenTms": 1697032965687,
  "properties": {
    "detectedName": "loading of page /clic-webapp/clic"
  },
  "tags": [],
  "icon": {
    "primaryIconType": "web"
  },
  "fromRelationships": {
    "isApplicationMethodOf": [
      {
        "id": "APPLICATION-B17D43675FCB4BD2",
        "type": "APPLICATION"
      }
    ],
    "isApplicationMethodOfGroup": [
      {
        "id": "APPLICATION_METHOD_GROUP-D3F738EEAEABC6AD",
        "type": "APPLICATION_METHOD_GROUP"
      }
    ]
  }
}
```

**Comment by mattBaumBeneva** [comment]
Querying .settings/objects with schema "builtin:rum.web.key-performance-metric-load-actions" and scope "APPLICATION-B17D43675FCB4BD2" only returns one Method, and not two:

```
{
  "items": [
    {
      "objectId": "vu9U3hXa3q0AAAABADNidWlsdGluOnJ1bS53ZWIua2V5LXBlcmZvcm1hbmNlLW1ldHJpYy1sb2FkLWFjdGlvbnMAC0FQUExJQ0FUSU9OABBCMTdENDM2NzVGQ0I0QkQyACRhMjhmNDhlMC00MTUyLTMwYmYtYmU0NC1iNzg5N2UwZDlkYmG-71TeFdrerQ",
      "scope": "APPLICATION-B17D43675FCB4BD2",
      "value": {
        "kpm": "VISUALLY_COMPLETE",
        "thresholds": {
          "toleratedThresholdSeconds": 3,
          "frustratingThresholdSeconds": 12
        },
        "fallbackThresholds": {
          "toleratedFallbackThresholdSeconds": 3,
          "frustratingFallbackThresholdSeconds": 12
        }
      }
    }
  ],
  "totalCount": 1,
  "pageSize": 100
}
```

**Comment by mattBaumBeneva** [comment]
We reproduced this issue with version 1.42.0.

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello @mattBaumBeneva,

I retraced the steps you've described. The only thing where my results differ from yours is, when querying for the already unsubscribed key user action via entities API. The Web Application was still listed within the `fromRelationships`. I can only assume, that relationships between entities are subject of "aging out over time".

But in any case - the reason why the KUA is showing up as the result of the data source is, that the provider specifies `now-3y` in order to not miss out on any entities. That behavior clashes with the fact, that Dynatrace doesn't simply delete KUAs that aren't assigned to a Web Application (metrics may have been produced for them already).

The only way to deal with this issue on short notice is to offer the attributes `from` and `to` for the data sources `dynatrace_entity` and `dynatrace_entities`. That at least gives you some sort of control over what is still valid and what not. The upcoming release will contain the additional attributes.

But on our todo list is also a better solution. Currently Key User Actions are getting configured WITHIN the resource for Web Applications - although configuration happens via a separate endpoint. My plan is to deprecate that block within `dynatrace_web_application` and instead introduce a resource `dynatrace_key_user_action`. ... and the next logical step would be to introduce a data source `dynatrace_key_user_action` that doesn't need to use the Monitored Entities API, but uses the same REST endpoint than the resource with the same name.

**Comment by mattBaumBeneva** [comment]
OK. Thanks!
