### ISSUE TITLE
Calculation of assignedEntity for a dashboard SLO tile unclear

### ISSUE THREAD

**Issue by agentreno** [dynatrace-oss/terraform-provider-dynatrace#353]
**Describe the bug**

I'm trying to create a dynatrace_json_dashboard resource with content exported from a manually created dashboard. There are tiles backed by an SLO, which seem to have the assignedEntities property on the Tile object to link it back to the SLO. Since I also create these with terraform, I'm templating that into the JSON.

However, after apply the tile is not linked to the SLO and fixing it manually produces a diff in the plan, changing it from the SLO ID to a base64 encoded string. Some of it is readable and it clearly contains the SLO ID, but there is other content there which is different to what the export created.

**To Reproduce**
1. Create a dashboard with an SLO tile 
2. Use the export facility to create a terraform resource from the dashboard
3. Create a new dashboard using this terraform resource
4. Observe broken tile not linked to SLO
5. Fix linkage manually in tile configuration
6. Generate terraform plan and observe diff with new base64 value for assignedEntity

**Expected behavior**

I would expect to interpolate an SLO ID into assignedEntities dashboard JSON and for that to be sufficient to link the tile to the SLO. Or, if this field should be calculated by the provider, I would expect to pass the SLO ID to a new field on the json_dashboard resource.

**Desktop (please complete the following information):**
 - OS: Ubuntu

**Comment by kishikawa12** [comment]
Hi @agentreno, I'm unfortunately unable to replicate this behavior. Are you able to set the following environment variables and send the generated logs to terraform@dynatrace.com?
```
DYNATRACE_DEBUG=true
DYNATRACE_LOG_HTTP=terraform-provider-dynatrace.http.log
DYNATRACE_HTTP_RESPONSE=true
```

Thanks!

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello @agentreno,

I unfortunately need to assume a few things here, just by looking at the HTTP logs you've provided. Let me know if my train of thought matches with what's happening in your environment.

You've exported your Dashboard using the statement `terraform_provider_dynatrace export -ref -datasources dynatrace_json_dashboard=<dashboardID>`. 

The resulting HCL code for the Dashboard therefore looks like this:
```
resource "dynatrace_json_dashboard" "Performance_X_owned_by_reinhard_pilz_dynatrace_com" {
   ...
          "assignedEntities": [
            "${data.dynatrace_slo.SLONAME.id}"
          ]
   ...
}
```

In other words: The HCL code of the dashboard refers to the SLO using the data source `dynatrace_slo`.

What's currently wrong about that is the "kind" of the ID that reference is getting replaced with - the base64 value you've mentioned: `vu9U3hXa3q0AAAABABZidWlsdGluOm1vbml0b3Jpbmcuc2xvAAZ0ZW5hbnQABnRlbmFudAAkYzFiMGVlOTUtMjA0YS0zMjgyLWJjMTItM2ZlYmE5MTdlYjNmvu9U3hXa3q0`

What SHOULD be used here is the attribute `legacy_id`. Your HCL code therefore needs to look like this:

```
resource "dynatrace_json_dashboard" "Performance_X_owned_by_reinhard_pilz_dynatrace_com" {
   ...
          "assignedEntities": [
            "${data.dynatrace_slo.SLONAME.legacy_id}"
          ]
   ...
}
```
A bit of background information about that attribute `legacy_id`: The Dynatrace REST API "knows" a couple of settings via two different kinds of IDs. We from the Terraform team call them the "Settings 2.0 ID" and the "Legacy ID". Depending on which resource you're referring to that setting from, it varies which one is "expected" by the REST API.
Our export functionality is in general aware of the rules here, but for SLOs (via data source) it behaves incorrectly.

The same thing applies by the way if you are not using a data source here, but are referring to the resource `dynatrace_slo_v2` - your HCL code should look like this, in order to work correctly:
```
resource "dynatrace_slo_v2" "SLONAME" {
   ...
}

resource "dynatrace_json_dashboard" "Performance_X_owned_by_reinhard_pilz_dynatrace_com" {
   ...
          "assignedEntities": [
            "${dynatrace_slo_v2.SLONAME.legacy_id}"
          ]
   ...
}
```

We will make sure that the export functionality produces the correct attribute `legacy_id` with the next release (you can expect that to get pushed out mid next week).
Until then, just edit the HCL code of your Dashboard and replace `.id` within the `assignedEntities` with `.legacy_id`.

Let me know if that helps,
Reinhard

**Comment by agentreno** [comment]
@Dynatrace-Reinhard-Pilz thanks a lot, this could well be the issue, it's the second approach I'm using (create SLO using resource, try to interpolate ID into json_dashboard), I'll try passing the legacy_id instead and update you shortly.

**Comment by agentreno** [comment]
@Dynatrace-Reinhard-Pilz yes passing legacy_id works now thanks. also I wasn't quite accurate in my last comment, I did originally use the export facility for the json_dashboard resource, so having that use the legacy ID in assignedEntities would be nice I think. Thanks for the assistance.

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Thanks for the confirmation. I'm closing the ticket. In case there are further difficulties, just drop us a message, and I'll re-open.
