### ISSUE TITLE
Azure Supporting Services

### ISSUE THREAD

**Issue by ozaal** [dynatrace-oss/terraform-provider-dynatrace#359]
**Describe the bug**
The provider is auto enabling the default supporting services [here](https://docs.dynatrace.com/docs/shortlink/azure-cloud-services-hub#azure-cloud-services-monitored-by-default), these services have conflicts with the newer supporting services, and this is causing issues when attempting to enable the newer supporting services.

Possible reason [here](https://github.com/dynatrace-oss/terraform-provider-dynatrace/blob/73472fa4207fa4325459ab1d48d51a1a4a6d2f26/dynatrace/api/v1/config/credentials/azure/settings/azure_credentials.go#L113)

**To Reproduce**
1. Enable any of the generic services, such as Azure Storage Blob Services

**Expected behavior**
Expect some sort of flag that will allow the user to choose whether to enable or disable the default supporting services

**Screenshot**

![image (22)](https://github.com/dynatrace-oss/terraform-provider-dynatrace/assets/25180650/48a3aba1-4d32-4ae2-b376-0a712e26ece4)

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello @ozaal, the real issue here is, that the REST API for configuring Azure Credentials doesn't offer that at the moment. Creating Azure Credentials ALWAYS produces the default set of services - no matter whether you specify an empty list or null for the supported services.

I've been reaching out to R&D about that already a while ago and didn't receive a definitive answer. We will take another look at the REST API here - it's possible that the behavior HAS been changed without us getting notified about it.

Until then I will keep this ticket open. Hoping to have a solution or at least a workaround for you soon.
