### ISSUE TITLE
cannot iterate over dynatrace_entities.entities

### ISSUE THREAD

**Issue by mattBaumBeneva** [dynatrace-oss/terraform-provider-dynatrace#366]
**Describe the bug**
This appears to be a regression 1.47.2.
When using the dynatrace_entities data source, Terraform returns an error during apply when using "count" or "for_each" on the entities field.

For instance:
```
data "dynatrace_entities" "process_groups" {
  entity_selector = "type(\"PROCESS_GROUP\"),entityName(\"${var.name}\"),mzId(\"${var.owner.legacy_id}\")"
}

resource "dynatrace_pg_alerting" "alerting" {
  count = length(coalesce(data.dynatrace_entities.process_groups.entities, []))
...
```

Will fail with:
```
09:57:04  │ Error: Invalid count argument
09:57:04  │ 
09:57:04  │   on ../../src/modules/blueprints/Processus/main.tf line 35, in resource "dynatrace_pg_alerting" "alerting":
09:57:04  │   35:   count = length(coalesce(data.dynatrace_entities.process_groups.entities, []))
09:57:04  │ 
09:57:04  │ The "count" value depends on resource attributes that cannot be determined
09:57:04  │ until apply, so Terraform cannot predict how many instances will be
09:57:04  │ created. To work around this, use the -target argument to first apply only
09:57:04  │ the resources that the count depends on.
```

I am fairly certain this was corrected in the past, and it used to pass without error.

**Expected behavior**
It should be possible to recover dynatrace_entities.entities and use the result in a subsequent "count" or "for_each", otherwise this data source is useless.

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello @mattBaumBeneva,

I just tried out this exact configuration with v1.47.2

```
variable "name" {
  type = string
  default = "go.exe"
}

variable "owner" {
  type = object({
    legacy_id = string
  })
  default = {
    legacy_id = "-3815199542646129164"
  }
}

data "dynatrace_entities" "process_groups" {
  entity_selector = "type(\"PROCESS_GROUP\"),entityName(\"${var.name}\"),mzId(\"${var.owner.legacy_id}\")"
}


resource "dynatrace_alerting" "alerting" {
  count = length(coalesce(data.dynatrace_entities.process_groups.entities, []))
  name            = "alerting-${count.index}"
  rules {
    rule {
      include_mode     = "INCLUDE_ALL"
      tags             = ["EnvironmentA:production", "Team:test"]
      delay_in_minutes = 0
      severity_level   = "AVAILABILITY"
    }
  }
}
```

and that worked out well.

Based on the error message it looks like the values of your variables `name` and `owner` have dependencies on resources that haven't gotten applied yet. My assumption here is, that it's a `dynatrace_management_zone_v2` - whichs `legacy_id` is **indeed** not available before the resource has gotten created.

Are saying the error doesn't manifest with v1.47.1?

**Comment by mattBaumBeneva** [comment]
In fact, our situation is a bit complicated. Ideally, the ID comes from a management_zone_v2, which was created with Terraform (should be fine).
But we also have a case where the MZ already exists in Terraform and its ID is recovered by:
```
data "dynatrace_management_zone" "mz" {
  name = var.owner.name
}
```

We then have a local that either has values from one source or the other, depending on the case.
We have run hundreds of builds with this logic, but it is failing since upgrading this morning.

**Comment by mattBaumBeneva** [comment]
@Dynatrace-Reinhard-Pilz , I have rolled back to 1.47.1 and we still have the issue. No idea why this started this morning. I will attempt to debug.

**Comment by mattBaumBeneva** [comment]
In our test, the MZ v2 is planned to be created, and its details (name, id, legacy_id) are passed to other modules in an output name "info", like so:
```
module "pg01" {
  source = "../../src/modules/blueprints/Processus"

  proprietaire = module.Equipe-test-01.info
  nom          = "cloudwatch-agent"
}
```

That data is then used in the entity selector (for ex.: mxId() ).
This has worked for a long time, with the MZ being created first, as its a dependency of the second module. I'm not sure why it isnt working any longer.

**Comment by mattBaumBeneva** [comment]
@Dynatrace-Reinhard-Pilz , your understanding seems right. Is there any reason MZ v2 would not be created first in this case?
This has pretty much always worked for us.

**Comment by Dynatrace-Reinhard-Pilz** [comment]
I've been doing some research since your last message - even was able to reproduce your error message. There's not even a need for submodules. The only thing needed is `dynatrace_entities` having a dependency on a not yet created resource.

The error message is a fairly common topic - both within the Hashicorp forums and on StackOverflow. None of the posts I've read through are showing EXACTLY the same situation like here. Therefore I'm also a bit lost when it comes to a solution.

One way you could approach this maybe:
* Define your management zone resources (likely based on a list of names)
* Define data sources for the management zones with these names
* Within `dynatrace_entities` refer exclusively to the DATA SOURCES - never to the resources

The tradeoff here is, of course, that you'll require multiple (at least 2) executions of `terraform apply` until everything has been created. Management Zones that don't exist yet during the first execution won't be covered by the management zone data sources during the first execution. But they will during the second one.

But I'm assuming a lot into the blue here - not knowing exactly what your whole configuration looks like. It's just an idea based on this statement within the error text:
```
To work around this, use the -target argument to first apply only the resources that the count depends on
```
