### ISSUE TITLE
dynatrace_aws_credentials without metrics configured resulting in error of having metrics configured.

### ISSUE THREAD

**Issue by FinUD** [dynatrace-oss/terraform-provider-dynatrace#367]
**Describe the bug**
As a result of https://github.com/dynatrace-oss/terraform-provider-dynatrace/issues/364 we have switched to just using the provider to manage the integration and not the configured services/metrics. We first ran an apply with no metrics configured to remove them. After this we noticed that some accounts didn't have all services removed, some still have auto-scaling left. After that we changed the value of `supporting_services_managed_in_dynatrace` to true and when attempting to run that with no metrics configured at all we got an error saying that we can't configure the auto-scaling service using this endpoint. 
![image](https://github.com/dynatrace-oss/terraform-provider-dynatrace/assets/97069792/6fab5e63-ef22-4368-b048-7aa664cd1c30)
We were running this against 57 different AWS accounts and we noticed that it was seemingly random which ones ended up with auto-scaling configured which makes it hard to reproduce. 

**To Reproduce**
1. First configure an AWS account using the `dynatrace_aws_credentials` resource. On this account, configure 71+ supporting services and their metrics. Use the `dynatrace_aws_credentials` resource for the metrics/services too.
2. Remove the metrics/services and apply the new configuration.
3. Change the value of `supporting_services_managed_in_dynatrace` to `true` and apply again.

**Expected behavior**
With no metrics/services configured the provider should not be attempting to configure any.

**Desktop (please complete the following information):**

OS: Windows 11
Version: 1.46.1

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello @FinUD,

Sorry to hear that you're still facing issues with AWS Services. Root cause for your continuing troubles are our attempts to keep the resource `dynatrace_aws_credentials` 100% backwards compatible for _possible_ users who are still maintaining their services via this resources instead of `dynatrace_aws_service`. 

We've now made the decision that we will remove the ability to maintain services using `dynatrace_aws_credentials`. The block `supporting_services_to_monitor` will get deprecated. The attribute `supporting_services_managed_in_dynatrace` won't have an effect. The attribute `remove_defaults` will remain, in order to enforce removing any default services upon create (won't have an effect for updates).

It's the only way we can avoid issues like the ones you've run into in the past.

We're planning to push out a release next week - it will include these changes.

**Comment by FinUD** [comment]
Hey @Dynatrace-Reinhard-Pilz, thanks for the update as always. Does this mean if you don't specify any `dynatrace_aws_service` resource blocks and only `dynatrace_aws_credentials` that it will remove any manually configured/API configured resources when you apply?

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Our plan is to change the resource like this:

The resource `dynatrace_aws_credentials` will ignore the services completely. Any services you're adding or removing via WebUI will be remain the same. Also, any services you're adding via resource `dynatrace_aws_service` will get ignored. The resource `dynatrace_aws_credentials` will simply not address them.

Just with one exception:
When Terraform CREATES an instance of `dynatrace_aws_credentials`, the target Dynatrace Environment usually creates a default set of services for these credentials.
If you set the attribute `remove_defaults` to `true`, you instruct Terraform to get rid of these services right after creation. Once that has happened `remove_default` won't have any further effect. Any subsequent updates for that instance of `dynatrace_aws_credentials` will ignore the services and will not attempt to modify the services.
