### ISSUE TITLE
Resource `dynatrace_credentials` needs to support the property `scopes`

### ISSUE THREAD

**Issue by Dynatrace-Reinhard-Pilz** [dynatrace-oss/terraform-provider-dynatrace#374]
Release notes of Dynatrace 
https://docs.dynatrace.com/docs/whats-new/release-notes/dynatrace-api/sprint-279#environment-api
signal that the property `scope` may soon get removed and replaced by `scopes`.

**Comment by kishikawa12** [comment]
Although officially deprecated, since the API still accepts `scope`, I'll tag that property as deprecated and point users to move to the new `scopes` element. Choosing not to create an "adapter" in this case since both options are currently available. 

Once `scopes` is available in the next release, it is recommended to move to this new property for any SaaS deployment or Managed version beyond v279.

Thanks!
