### ISSUE TITLE
Timing issue when creating Web Application and Application Detection Rule in the same Apply run

### ISSUE THREAD

**Issue by mattBaumBeneva** [dynatrace-oss/terraform-provider-dynatrace#378]
**Describe the bug**
In recent releases of the provider, Apply fails when creating a Web Application and immediately configuring an application_detection_rule. We obtain an error like:

```
15:15:18  │ Error: Given property 'applicationId' with value: 'APPLICATION-50B4043E6218A48D' is not a valid value in datasource. Value must be one of [APPLICATION-EE0C83DF34703FC3, APPLICATION-CBC013E92D72B52C, APPLICATION-B44E988BE738E747, APPLICATION-DB81E5A9158754D9, APPLICATION-B691542791223EBD, APPLICATION-1FB04133BE3722D0, APPLICATION-E445C2D91308365D, APPLICATION-708B72B3AC266472, APPLICATION-E099B23387BDE327, APPLICATION-2F4D8152711CB21F, APPLICATION-E2228C8C7104C318, APPLICATION-53B13F342A3B4460, APPLICATION-63BC5EABE0D7B4DD, APPLICATION-03E844D58FAAB023, APPLICATION-A48D4E6B7C393C67, APPLICATION-8B614945144A3E21, APPLICATION-FECE2A3B4485F586, APPLICATION-6DEEEA95D2D55DD2, APPLICATION-00BDB890357EA077]
15:15:18  │ 
15:15:18  │   with module.Application_test-de-base.dynatrace_application_detection_rule.application["/test-terraform"],
15:15:18  │   on ../../src/modules/blueprints/Application/main.tf line 302, in resource "dynatrace_application_detection_rule" "application":
15:15:18  │  302: resource "dynatrace_application_detection_rule" "application" {
```

If we run apply again, configuration completes correctly. The Provider no longer seems to wait for Applications to be available before proceeding.

Our code looks like:
```
resource "dynatrace_application_detection_rule" "application" {
  for_each               = var.detection_url
  application_identifier = dynatrace_web_application.application.id
  filter_config {
    application_match_target = "URL"
    application_match_type   = "CONTAINS"
    pattern                  = each.value
  }
}
```

**Expected behavior**
It should be possible to configure detection rules in the same apply run that creates the application.

**Comment by mattBaumBeneva** [comment]
We are using the latest provider version

**Comment by kishikawa12** [comment]
Hi @mattBaumBeneva,
This issue sounded familiar to a previous one in the past so I went looking at the resource and our GitHub issues. 

The related issue was #225 and the fix was to increase the number of retries to confirm creation. With the current code, there's a default set where we're validating that we're successfully retrieving the newly created application 60 times. This value can be increased with an environment variable `DYNATRACE_CREATE_CONFIRM_WEB_APPLICATION` to up to 300 times.

We'll continue to give some thought to see if there's any other way we can improve this resource. In the meantime, are you able to increase the number and see if that resolves your issue?

Thanks!

**Comment by mattBaumBeneva** [comment]
We can try that and get back to you with the results.

**Comment by mattBaumBeneva** [comment]
This indeed seems to stabilize the behavior for us. I set the variable to the max allowed (300).
