### ISSUE TITLE
Workflow execution in error after terraform apply

### ISSUE THREAD

**Issue by MaudVandevelde** [dynatrace-oss/terraform-provider-dynatrace#387]
**Describe the bug**
Worklow are in error after being created with terraform. All the first tasks (in my case there are 3 task on first steps) have the following error:

```
An error occurred: {"code": 540, "message": "Execution crashed.", "details": {"type": "UNCAUGHT_EXCEPTION", "message": "Uncaught (in promise) ExecutionsClient.getTaskExecution:200: ExecutionsClient.getTaskExecution:200: Response does not match expected datatype: TypeError: Cannot destructure property 'x' of '$model' as it is null.", "details": {"lineNumber": 2456, "startColumn": 15, "stack": "ExecutionsClient.getTaskExecution:200: ExecutionsClient.getTaskExecution:200: Response does not match expected datatype: TypeError: Cannot destructure property 'x' of '$model' as it is null.\n    at ExecutionsClient.getTaskExecution (file:///opt/sdk_modules/@dynatrace-sdk/client-automation/esm/index.js:2456:15)\n    at eventLoopTick (ext:core/01_core.js:183:11)\n    at async Object.result (file:///opt/sdk_modules/@dynatrace-sdk/automation-utils/esm/index.js:22:21)\n    at async default (file:///script.ts:15:35)"}}}
```

If I edit just one block ,  for example adding a space in js, saving, removing the space, saving , then relaunch the execution is ok. So I know that there is no issue with the workflow itself

**Expected behavior**
workflow execution should be ok without having anything to do after terraform execution

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello @MaudVandevelde,

Could you provide the HCL code for the workflow you're trying to apply? We've tried with a couple of simple samples but cannot reproduce the issue. It's likely something that is included within your use case where we're sending something flawed.

Feel free to send to terraform@dynatrace.com - anyone from our team will be able to pick it up then.

thanks,
Reinhard

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello @MaudVandevelde,

Would you be able to dig up the JS file for me that deals with this `$model` object?
I'm wondering whether the file encoding is perhaps different than expected - perhaps as simple as tabs instead of spaces. I'd like to take a closer look into that, since you're reading the contents of your Javascript Actions from disk.

thanks,
Reinhard

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello Maud,

First, thank you for sending the complete module.

After playing around with it a bit (and carefully reading through your initial problem description) I finally realized that I was poking around at the completely wrong direction. My assumption so until now had been, that Terraform for some reason encodes the JS code the wrong way - which eventually produces ill formatted JS code within the resulting workflow.

What I now realize is, that your statement

```
adding a space in js, saving, removing the space, saving , then relaunch
```

just describes the process of forcing Terraform to **update** the Workflow Settings at least once, am I correct?

Also, because I was now able to take a look at the .js files your modul is based on, it's clear to me that the error message

```
Cannot destructure property 'x' of '$model' as it is null
```

cannot originate from YOUR Javascript code. 

What I am tempted to blame the issue on is the usage of the data source `dynatrace_entities` for finding the `guardianIds`. The REST endpoint used for that data source has given us headaches in the past already.

But in order to be sure about that I unfortunately need to ask again for a bit more data. With the following environment variables defined

```
DYNATRACE_DEBUG=true
DYNATRACE_HTTP_RESPONSE=true
DYNATRACE_LOG_HTTP=terraform-provider-dynatrace.http.log
```

the Terraform Provider dumps HTTP traffic and debug information into the files `terraform-provider-dynatrace.log`, `terraform-provider-dynatrace.http.log` and `terraform-provider-dynatrace.http.err.log`.

The entries of interest will look similar to this:
```
2024/02/12 12:32:33 POST https://siz65484.apps.dynatrace.com/platform/automation/v1/workflows
2024/02/12 12:32:33    {"actor":"703
2024/02/12 12:32:33 PUT https://siz65484.apps.dynatrace.com/platform/automation/v1/workflows
2024/02/12 12:32:33    {"actor":"703
```

As usual feel free to send any data to terraform@dynatrace.com.

**Comment by MaudVandevelde** [comment]
Hello,
When I say : "adding a space in js, saving, removing the space, saving , then relaunch " , it is done from dynatrace ui.
The complete process is:
- Deployment thanks to terraform:  I have the error I mentionned in the ticket
- From the UI I do some modification in one of the block, and then remove the modification : No more terraform at this point
And it works.

I will send you the log .
Regards,
Maud

**Comment by MaudVandevelde** [comment]
I sent you the log.
Regarding the dynatrace_entities bloc to get the guardian I am not sure that this is the error . In fact this bloc is ok and can be executed. blocs in error are js block:
![js in error](https://github.com/dynatrace-oss/terraform-provider-dynatrace/assets/91145303/03248ec7-1d1f-485a-b62d-a2c447cd2a69)

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Quick summary of our finding during todays call:
* Your workflow contains a dynamic section for creating a task per guardian
* Because of that you're omitting the `position` block - understandably because otherwise you would have to come up with some sort of algorithm for different positions
* For a reason we don't know yet, Dynatrace runs into the error `Cannot destructure property 'x' of '$model' as it is null."` because of that
* When making small modifications to the Workflow and then saving it, Dynatrace auto-corrects the missing position

We've seen, that it is possible to specify the same `position` for multiple tasks (the WebUI prevents that, but the REST API accepts it). So, although the results are visually not entirely satisfying that allows you to work around the issue temporarily.

In order to resolve the problem properly I can see two options:
a) We will look into ways for automatically populating the `position` block in case it is missing within the Terraform Provider. 
b) Dynatrace R&D could also make some changes when receiving the workflows and automatically apply the validation it applies during "resaving" workflows.

We will keep this ticket open until we know which option works best.

Thanks again for joining our call today. It saved us a lot of time!

**Comment by MaudVandevelde** [comment]
For your information I have done the following modifications in terraform:
I have added a position in the guardian list variable:

locals {

  guardian_list = [for index, entity in data.dynatrace_entities.application_guardian.entities :
    {
      name : entity.display_name,
      guardianId : [for tag in entity.tags[0].tag : tag.value if tag.key == "guardian_id"]
      position : index
    }
  ]

then the position is now:
        position {
          x = item.value["position"]
          y = 1
        }

Now it works well and it is visually ok :-)
Thank you very much

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello @MaudVandevelde,

Glad to read that utilizing `item.value["position"]` is a usable workaround for the time being.

I also have reached out to R&D about this and they have identified the underlying bug here. The will take care of it in the upcoming releases of Dynatrace.

I remember that during our call I considered to add custom code to the provider that generates position blocks automatically, but because you're apparently fine with using the workaround you've found and because in the near future even that won't be necessary anymore, it doesn't sound like a necessary effort.

Just drop us a message in case you disagree and we will re-open this ticket.
