### ISSUE TITLE
dynatrace.com/com/dynatrace provider not working

### ISSUE THREAD

**Issue by Karthikeyanraman94** [dynatrace-oss/terraform-provider-dynatrace#39]
In docs its mentioned as below
```
terraform {
    required_version = "> 0.13.0"
    required_providers {
        dynatrace = {
              source = "dynatrace.com/com/dynatrace"
              version = "1.2.1"
        }
    }
} 
```
```
throws 17:25:09  Error: Invalid provider registry host
17:25:09  
17:25:09  The host "dynatrace.com" given in in provider source address
17:25:09  "dynatrace.com/com/dynatrace" does not offer a Terraform provider registry.
17:25:09  
```

But working one is as below
```
terraform {
    required_version = "> 0.13.0"
    required_providers {
        dynatrace = {
            source = "dynatrace-oss/dynatrace"
            version = "1.2.1"
        }
    }
} 
```

**Comment by Dynatrace-Reinhard-Pilz** [comment]
@Karthikeyanraman94 what version of the terraform CLI are you using?

**Comment by Karthikeyanraman94** [comment]
terraform:0.13.4

**Comment by Dynatrace-Reinhard-Pilz** [comment]
@Karthikeyanraman94 your issues stem from the fact that haven't installed the binaries manually like it's mentioned [here](https://github.com/dynatrace-oss/terraform-provider-dynatrace/blob/main/README.md).
You are simply asking the terraform cli to download the required provider for you - which is admittedly the best route to go.
We will update the documentation in order to avoid confusion in the future.

Thanks for the hint!

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello @Karthikeyanraman94 
The updated [Readme](https://github.com/dynatrace-oss/terraform-provider-dynatrace#readme) now contains instructions for referring to the Terraform Registry instead of manual installation.
Thanks for hinting that mistake, much appreciated!
