### ISSUE TITLE
resource "dynatrace_aws_service" does not apply required metrics/dimensions

### ISSUE THREAD

**Issue by jsoellner** [dynatrace-oss/terraform-provider-dynatrace#398]
**Describe the bug**
When creating a dynatrace_aws_service resource, with the intention of defining a custom set of metrics to apply to a service that is NOT a built-in service, the "metrics" input block is ignored, even when "use_recommended_metrics" is set of false.

**To Reproduce**
1. Create "dynatrace_aws_service" resource
2. Specify desired metrics and dimensions using correct metrics input nested schema
3. Check Dynatrace UI - your desired configuration will not have been applied

**Expected behavior**
I expect to be able to define the metrics and dimensions I want to monitor for each service using the "metrics" input.

**Screenshots**

**Additional context**
Using provider version 1.49.0
![Screenshot 2024-02-09 at 15 41 43](https://github.com/dynatrace-oss/terraform-provider-dynatrace/assets/95619740/09d4f84e-0a85-4593-965e-154c0c7423ad)
![Screenshot 2024-02-09 at 15 42 16](https://github.com/dynatrace-oss/terraform-provider-dynatrace/assets/95619740/800fba32-9fb6-4217-8d5c-802463b953b5)

**Comment by jsoellner** [comment]
example plan output screenshot added, along with an additional screenshot showing that after the apply, the changes have not been applied - in this case, the additional dimensions have not been added

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello @jsoellner, 

I am able to reproduce your issue. It's something we cannot solve with in the Terraform Provider - apparently the REST API "swallows" configuration for metrics that is allowed according to the documentation but differs from defaults.

I've reached out internally to R&D for clarification. Until I get a response I'll keep this ticket open - perhaps they come back with a suggestion for a workaround

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hi @jsoellner,

R&D indeed came back to me with a workaround.

What happens here is, that the order of the dimensions as specified in the configuration DOES matter here - and if specified in the wrong order, the behavior as observed right now is to be expected.

I just committed a change so that the Provider treats the `dimensions` as an ordered list (currently unordered).
That unfortunately won't be bullet proof. Configuration like that one
```
  metric {
    dimensions = [
      "ApiName",
      "Method",
      "Resource",
      "Stage",
    ]
    name = "4XXError"
    statistic = "SUM"
  }
```
will still produce the same behavior - because the dimensions are in the wrong order.
You will have to make sure that the order looks like this.
```
  metric {
    dimensions = [
      "ApiName",
      "Stage",
      "Resource",
      "Method"
    ]
    name = "4XXError"
    statistic = "SUM"
  }
```
The exact order that's expected can be found for every service on its page in the [Dynatrace Documentation](https://docs.dynatrace.com/docs/setup-and-configuration/setup-on-cloud-platforms/amazon-web-services/amazon-web-services-integrations/cloudwatch-metrics/aws-all-services/api-gateway#available-metrics).

So far about a short term solution - which unfortunately also requires an update on the Terraform Provider.

Dynatrace R&D is however going to fix the behavior on the REST API. As soon as that has happened we will change the `dimensions` attribute back to an unsorted list.

**Comment by jsoellner** [comment]
Hi @Dynatrace-Reinhard-Pilz thanks for your responses, much appreciated!
