### ISSUE TITLE
Custom anomalies detection not working at all

### ISSUE THREAD

**Issue by Karthikeyanraman94** [dynatrace-oss/terraform-provider-dynatrace#41]
Issue 1:  Having a More Race condition than any other resource and it corrupts the tfstate file as discussed in previous Issue

Issue2:  Even though the data's are getting added correctly, we are facing the issue

```
module "custom_anamolies" {
    source = "../modules/dynatrace/customAnamolies"
    staticCustomAnamolies = {
        "custom_anamolies_test_fivexx" = {
            staticCustomAnamoliesName = "ai_test_fivexx",
            aggregation_type = "VALUE",
            metric_id = "builtin:service.errors.fivexx.count",
            scope_operator = "CONTEXTLESS",
            scope_value = "test-services",
            alert_condition = "ABOVE"
            alerting_on_missing_data = "false",
            dealerting_samples = "5",
            samples = "5",
            threshold = "10",
            unit = "COUNT"
            violating_samples = "3"
        }
    }
}
```
This always throws the error:
```
21:22:03  Error: {
21:22:03    "code": 400,
21:22:03    "message": "Constraints violated.",
21:22:03    "constraintViolations": [
21:22:03      {
21:22:03        "parameterLocation": "PAYLOAD_BODY",
21:22:03        "location": "",
21:22:03        "message": "must be greater than or equal to 3",
21:22:03        "path": "monitoringStrategy.samples"
21:22:03      },
21:22:03      {
21:22:03        "parameterLocation": "PAYLOAD_BODY",
21:22:03        "location": "",
21:22:03        "message": "The 'violatingSamples' number must be in between 1 and the given 'samples' number.",
21:22:03        "path": "monitoringStrategy.violatingSamples"
21:22:03      }
21:22:03    ]
21:22:03  }
```

**Comment by Dynatrace-Reinhard-Pilz** [comment]
@Karthikeyanraman94 
In order to avoid race conditions you currently should specify `-parallelism=1` when using `terraform apply`. This is a limitation of the Dynatrace REST API. Creating more than one configuration at the same time leads configuration not being created at all. We've already filed an internal bug report, but until that limitation is being dealt with `-parallelism=1` is the best solution.

About your sample configuration:
The attributes `dealerting_samples`, `samples`, etc. should be specified as Numbers. You're specifying them as strings. Looks that's why the default `int` value of `0` is being assumed by the cli.

In general I'm a bit surprised that the terraform CLI doesn't complain about the wrong data types being used for attributes.
I'll look into how to enforce that.

**Comment by Dynatrace-Reinhard-Pilz** [comment]
@Karthikeyanraman94 would you be available some time next week, so we can take a look at your configuration together? Your module differs significantly from a plain `.tf` file and I don't want you to share that here on public GitHub.
Feel free to reach out to me at reinhard.pilz@dynatrace.com so we can find a suitable time.

**Comment by Karthikeyanraman94** [comment]
Even If I change it to number, its still throwing the same error

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello @Karthikeyanraman94,

The issue you've experiencing are followup error of #42. Release [v1.2.2](https://github.com/dynatrace-oss/terraform-provider-dynatrace/releases/tag/v1.2.2) fixes this problem.
