### ISSUE TITLE
[Issue] module.dynatrace_builtin_process_monitoring.dynatrace_builtin_process_monitoring.go_static apply error

### ISSUE THREAD

**Issue by JayChanggithub** [dynatrace-oss/terraform-provider-dynatrace#438]
I encountered an issue while executing terraform apply with the dynatrace_builtin_process_monitoring module. The error message states

````
Error: Given property '-71' with value: 'null' does not comply with required NonNull of schema

with module.dynatrace_builtin_process_monitoring.dynatrace_builtin_process_monitoring.go_static
````

Below is the code snippet for the dynatrace_builtin_process_monitoring resource:

```
resource "dynatrace_builtin_process_monitoring" "go_static" {
  go_static     = false
  host_group_id = "environment"
}
```

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello @JayChanggithub,

Does the error go away when with this configuration?

```
resource "dynatrace_builtin_process_monitoring" "go_static" {
  go_static     = false
  exe_openhandlecollector = true
  host_group_id = "environment"
}
```

What version of the provider are you using? Is it at least [v1.54.0](https://github.com/dynatrace-oss/terraform-provider-dynatrace/releases/tag/v1.54.0)? I'm asking because since that version the provider is sending a special parameter to the REST API, that *should* prevent errors in such a case.

Also, could you run your example with these environment variables defined?
```
DYNATRACE_DEBUG=true
DYNATRACE_LOG_HTTP=terraform-provider-dynatrace.http.log
DYNATRACE_HTTP_RESPONSE=true
```
That would produce a file `terraform-provider-dynatrace.http.log` (and potentially `terraform-provider-dynatrace.http.err.log`). These files would give us insight into the actual HTTP traffic between Terraform and the Dynatrace Cluster.

thanks,
Reinhard

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Thanks for your feedback. With v1.54.0 you also shouldn't have to specify `exe_openhandlecollector`.
