### ISSUE TITLE
Present a data source for Lambda layers

### ISSUE THREAD

**Issue by edfenergy-stevebowerman** [dynatrace-oss/terraform-provider-dynatrace#445]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
We are looking to automate more of our Dynatrace deployment and part of this includes getting better at staying up to date with using the right Lamba layers.

https://docs.dynatrace.com/docs/dynatrace-api/environment-api/deployment/oneagent/get-latest-version-lambda

**Describe alternatives you've considered**
Call the underlying DT API's directly

**Additional context**
None

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hi @edfenergy-stevebowerman ,
Sounds like a good candidate for another Data Source. We'll try to get that implemented in one of the next releases.

**Comment by kishikawa12** [comment]
Hi @edfenergy-stevebowerman,

We typically stay away from deployment based use cases since our Terraform provider focus is on managing configuration, but since this is an inquiry for a simple data source I figured we can make an exception. The data source `dynatrace_lambda_agent_version` will be available in the next release.

Hope that helps!

**Comment by edfenergy-stevebowerman** [comment]
Awesome, thank you!
