### ISSUE TITLE
Public Document Support

### ISSUE THREAD

**Issue by Dynatrace-Reinhard-Pilz** [dynatrace-oss/terraform-provider-dynatrace#448]
The REST API for Automation is expected to offer an additional method (PATCH) for making the Documents a user owns "public".
We should introduced an additional resource `dynatrace_public_document` that refers to existing `dynatrace_document` and sets public yes/no.

**Comment by caleb-long-vad2r4** [comment]
Hey @Dynatrace-Reinhard-Pilz, will the existence of this resource allow the explicit setting of the document owner? I have since gotten the dynatrace_document with dynatrace_direct_shares set up, but this of course sets the owner of the document by default to whoever created the automation client. If this is unavoidable, I understand. Just wanted to follow up on what will be possible with this coming resource.

Thanks again for all your help!

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hell Caleb, I'm afraid it works like you described - the owner will still be the user for which the Automation Client has been created. So far I haven't gotten any word about the possibility to maintain documents as "administrator" where you're allowed to determine the owner. It's something I would personally would also welcome - the current functionality doesn't really allow document management centrally.
I will keep you up to date in case something like that opens up. We would make sure that the functionality will be available in Terraform also.

**Comment by caleb-long-vad2r4** [comment]
@Dynatrace-Reinhard-Pilz Sounds good, thanks for the information on this!

**Comment by Reinhard-Pilz-Dynatrace** [comment]
Setting documents to public has already been implemented
