### ISSUE TITLE
BUG: download error on MAC "too many open files error"

### ISSUE THREAD

**Issue by colinsidi** [dynatrace-oss/terraform-provider-dynatrace#45]
During download process, we are getting this error:

too many open files error

checking ulimit -n
256

setting ulimit -n 10000
allows this download process to work

**Comment by Dynatrace-Reinhard-Pilz** [comment]
We are planning to add a bit more control over what configuration files should get downloaded with one of our upcoming features. That already should reduce the number of open files. 
Nevertheless I would expect any already written files to get released automatically. I will run some tests to check whether there are perhaps some resources that leave some dangling file pointers.

**Comment by Dynatrace-Reinhard-Pilz** [comment]
v1.2.2
Latest
10 minutes ago

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello @colinsidi,
With release [v1.2.2](https://github.com/dynatrace-oss/terraform-provider-dynatrace/releases/tag/v1.2.2) all the resulting files are getting closed as early as possible now.
Since I was not able to reproduce this issue locally, please don't hesitate to reopen this issue, in case that doesn't solve your difficulties.
