### ISSUE TITLE
Dashboard with management zone id's are not getting

### ISSUE THREAD

**Issue by Karthikeyanraman94** [dynatrace-oss/terraform-provider-dynatrace#47]
We have the dashboards which contains tiles that's filtered by management zone, when downloaded through the DT TF utility
the tiles having management zone id, I think this varies w.r.t DT environment we connect to, if we are connecting to diff DT env and tries to apply, the management zone name will be same and the ID may differ, which could be the cause for this issue
any Idea to solve this?
```
   tile {
    name = ""
    configured = true
    tile_type = "CUSTOM_CHARTING"
    bounds {
      height = 228
      left = 1102
      top = 1786
      width = 380
    }
    filter {
      management_zone {
        name = "test"
        id = "7205384435779584767"
      }
    }
```
```
13:50:17  Error: {
13:50:17    "code": 400,
13:50:17    "message": "Constraints violated.",
13:50:17    "constraintViolations": [
13:50:17      {
13:50:17        "parameterLocation": "PAYLOAD_BODY",
13:50:17        "location": "",
13:50:17        "message": "may not be null",
13:50:17        "path": "dashboardMetadata.dashboardFilter.managementZone.id"
13:50:17      }
13:50:17    ]
13:50:17  }
```

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Like for #46 I will find the time until tomorrow to debug this.

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello @Karthikeyanraman94 

You're right, the underlying issue here is, that most configuration IDs are unique across environments. This means that certain properties (like Management Zone IDs) cannot get transferred without modification to other environments.

I AM aware of that limitation. I also have a couple of ideas how to work around that:
a) allowing to configure the management zone name instead of the ID and before sending the data via REST API to Dynatrace resolving the actual ID
b) Providing a Data Source for Management Zones so users can fill in the correct one

The easier solution is likely b) while the one with more convenience for the user will be a).

I will keep this ticket open until I'm working actively on that topic.

**Comment by Karthikeyanraman94** [comment]
@Dynatrace-Reinhard-Pilz : Please help us with the update on this

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Apologies @kamiljsokolowski, it looks like I completely mistook this issue as an enhancement and just stumbled across this bug by accident again.
Release [v1.6.1](https://github.com/dynatrace-oss/terraform-provider-dynatrace/releases/tag/v1.6.1) fixes this bug. The Management Zone ID is now getting serialized properly.
