### ISSUE TITLE
Documentation regarding component excluded form the export

### ISSUE THREAD

**Issue by MaudVandevelde** [dynatrace-oss/terraform-provider-dynatrace#471]
In [terraform provider documentation](https://registry.terraform.io/providers/dynatrace-oss/dynatrace/latest/docs/guides/export-v2 ) there is a note saying: 
NOTE: Dashboards (because there could be thousands of them) are currently excluded from the export unless the resource is directly specified in the command line arguments. 

When I read this note, I understand that dashboard is the unique ressource concerned by the exclusion. But I know that there is other ressources which are note included in the export. For example:  in [dynatrace_automation_workflow](https://registry.terraform.io/providers/dynatrace-oss/dynatrace/latest/docs/resources/automation_workflow)  there is a note saying  that: This resource is excluded by default in the export utility

Is there a command which allow to export ALL the component? or is it possible to get the list of all excluded component?

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello @MaudVandevelde 

Coincidentally another customer asked a very similar question a couple of days ago.

The next release will offer the ability to call `terraform-provider-dynatrace -export -list-exclusions` in order to get such a list.

If you'd like to see the output right now, please take a look at the [other ticket](https://github.com/dynatrace-oss/terraform-provider-dynatrace/issues/469#issuecomment-2144909927).

We will also talk internally about the possibility to include resources in an export despite the fact that they're excluded. I know that right now there is no real way to specify: "Export everything that's included by default AND Dashboards AND Workflows". I will keep that ticket open until we've synced internally about that topic so I have an answer for you.

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello @MaudVandevelde,

The upcoming release of the provider will contain two additional features for the export.

* `terraform-provider-dynatrace -export -list-exclusions` lists the resources that are not included by default (i.e. when executing `terraform-provider-dynatrace -export` without any resources specified
* `terraform-provider-dynatrace -export * <resource> <resource>` allows you to export all resource that are included by default and in addition to that the resources you have specified. 

Let me know in case that solution doesn't resolve your question and I will re-open the ticket.

best regards,
Reinhard
