### ISSUE TITLE
Trying to create anomaly detector but receiving status code 0 (expected: 200): 

### ISSUE THREAD

**Issue by PriyaSivaraj1987** [dynatrace-oss/terraform-provider-dynatrace#473]
**Describe the bug**
Trying to deploy anomaly detector using this provider but receive this status code 0 which is hard to interpret.

**To Reproduce**
```
+ resource "dynatrace_davis_anomaly_detectors" "anomaly_detector" {
      + description = "Created problems if the number of errors in the mmw-emailer-lambda exceeds the threshold"
      + enabled     = true
      + id          = (known after apply)
      + source      = "Davis Anomaly Detection"
      + title       = "Anomaly detection for lambda error logs"

      + analyzer {
          + name = "dt.statistics.ui.anomaly_detection.StaticThresholdAnomalyDetectionAnalyzer"

          + input {
              + analyzer_input_field {
                  + key   = "alertCondition"
                  + value = "ABOVE"
                }
              + analyzer_input_field {
                  + key   = "alertOnMissingData"
                  + value = "false"
                }
              + analyzer_input_field {
                  + key   = "dealertingSamples"
                  + value = "5"
                }
              + analyzer_input_field {
                  + key   = "query"
                  + value = "fetch logs\\n| filter aws.account.id == \"xxxxxxxxx\"\\n| filter aws.log_group == \"/aws/lambda/xxxx\"\\n| filter loglevel == \"ERROR\"\\n| makeTimeseries count = count(default: 0), interval:1m"
                }
              + analyzer_input_field {
                  + key   = "slidingWindow"
                  + value = "5"
                }
              + analyzer_input_field {
                  + key   = "threshold"
                  + value = "1"
                }
              + analyzer_input_field {
                  + key   = "violatingSamples"
                  + value = "1"
                }
            }
        }

      + event_template {
          + properties {
              + property {
                  + key   = "dt.source_entity"
                  + value = "{dims:dt.source_entity}"
                }
              + property {
                  + key   = "event.type"
                  + value = "CUSTOM_ALERT"
                }
              + property {
                  + key   = "event.name"
                  + value = "lambda-log-errors"
                }
              + property {
                  + key   = "event.description"
                  + value = "lambda-log-errors"
                }
              + property {
                  + key   = "owner"
                  + value = "xxx"
                }
              + property {
                  + key   = "environment"
                  + value = "test"
                }
            }
        }

      + execution_settings {}
    }
```

**Expected behavior**
Was able to create the resource through UI with the values mentioned above without any issue.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello @PriyaSivaraj1987 

I just noticed that you were not getting back an error because your configuration was malformed. Apologies for investigating at first into the wrong direction.

What's apparently missing in your case are credentials for authenticating via OAuth.
That's special for some resources, including [dynatrace_davis_anomaly_detectors](https://registry.terraform.io/providers/dynatrace-oss/dynatrace/latest/docs/resources/davis_anomaly_detectors). Reason behind that is, that for some resources the Dynatrace Cluster, in order to validate your configuration, needs to execute some routines. 

Documentation for how to create an OAuth Client can be found [here](https://docs.dynatrace.com/docs/manage/configuration-as-code/terraform/guides/create-oauth-client).

Once the OAuth Client is created you can configure the Terraform Provider using the Environment variables `DT_CLIENT_ID` and `DT_CLIENT_SECRET`.

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello @PriyaSivaraj1987 

The upcoming release of the provider will print out the correct error message in this case. If you have further questions regarding OAuth Clients, please reach out to us and we will re-open this ticket.

regards,
Reinhard
