### ISSUE TITLE
Provider failed to plan correctly for dynatrace_business_events_oneagent

### ISSUE THREAD

**Issue by hhminh** [dynatrace-oss/terraform-provider-dynatrace#511]
**Describe the bug**
Provider failed to plan correctly for dynatrace_business_events_oneagent.

**To Reproduce**
1. Create a dynatrace_business_events_oneagent
2. Apply it once
3. Apply again and it will not be able to see the trigger already exists and try to delete, re-create same trigger and even add an empty trigger block after. This does not always happen I have seen this happens on 1/3 of the blocks not all of them. This made the apply to fail due to the extra empty block on top of the unnecessary change detected:

![image](https://github.com/user-attachments/assets/5041fd3f-4d9b-446c-9801-b9bd9abf88d6)

 
See screenshot section for the actual plan :

**Expected behavior**
It should detect that there is no change

**Screenshots**
![image](https://github.com/user-attachments/assets/6968491b-fa8f-450d-a42a-e5c54b379931)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version:  1.61.0

**Additional context**

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello @hhminh,

Root cause here is a bug in the Terraform Plugin SDK. We unfortunately rarely can predict which resources are affected - hence we can only react once customers are noticing a problem with empty blocks.

The issue will be fixed with the upcoming release of the provider.

best regards,
Reinhard
