### ISSUE TITLE
dashboard with dynatrace_document resource is not assigning the owner

### ISSUE THREAD

**Issue by jbecho** [dynatrace-oss/terraform-provider-dynatrace#517]
**Describe the bug**
When creating a dashboard with the `dynatrace_document` resource, the terraform plan/apply shows the owner ID being correctly assigned but it is actually being assigned to the owner of the OAuth token.  Subsequent plans/applies show drift and will attempt to set to the correct owner but it keeps the owner of the OAuth token.

Similar to [#457](https://github.com/dynatrace-oss/terraform-provider-dynatrace/issues/457) but in this case we are explicitly setting the owner [per the provider documentation](https://registry.terraform.io/providers/dynatrace-oss/dynatrace/1.55.0/docs/resources/document#owner).  

Also similar to [#448](https://github.com/dynatrace-oss/terraform-provider-dynatrace/issues/448) but we aren't requesting a public document.  

**To Reproduce**

1. Create an OAuth token with one user and configure provider.
2. Apply below terraform using another user's email in the data call for the owner

```
data "dynatrace_iam_user" "dashboard_owner" {
  email = "john.doe@domain.com"
}

resource "dynatrace_document" "test_dashboard" {
    type    = "dashboard"
    name    = "My Test Dashboard"
    owner   = data.dynatrace_iam_user.dashboard_owner.uid
    content = file("${path.module}/dashboard-jsons/test_dashboard.json")
}
```

3, The dashboard will be unavailable to the user in the UI
4. Apply direct_share to give read or read-write permissions

```
resource "dynatrace_direct_shares" "test" {
  count = var.env == "test" ? 0 : 1
  document_id = dynatrace_document.test_dashboard[count.index].id
  access      = "read-write"

  recipients {
    recipient {
      id   = data.dynatrace_iam_user.dashboard_owner.uid
      type = "user"
    }
  }
}
````
    
6.  The dashboard is now visible in the UI but the owner is assigned to the creator of the OAuth token

**Expected behavior**
The owner of the dashboard should be assigned to the user specified in the terraform [per the provider documentation](https://registry.terraform.io/providers/dynatrace-oss/dynatrace/1.55.0/docs/resources/document#owner)

**Screenshots**
N/A

**Additional context**
Using provider version 1.64.0 with Scalr remote apply using service account

**Comment by kishikawa12** [comment]
Hi @jbecho,

The attribute can be a bit misleading, unfortunately at the current moment, you can only create (and manage) documents tied to the service user. 

A temporary workaround would be to create the dashboard via the service user and then utilize the [dynatrace_direct_shares](https://registry.terraform.io/providers/dynatrace-oss/dynatrace/latest/docs/resources/direct_shares) resource to share it out to the appropriate users/groups.

There's also an "admin mode" feature planned to be released in a month or two that will allow you to manage dashboards of other owners. We plan to introduce this feature in our provider once this becomes available.

I'll close this ticket for now since this is the currently expected API behavior and should be resolved with the admin mode in a future release. Please feel free to reopen as necessary, thanks!
