### ISSUE TITLE
Question: Will provider configuration be deprecated?

### ISSUE THREAD

**Issue by MohammedZia-IPO** [dynatrace-oss/terraform-provider-dynatrace#558]
Hi,

We're currently configuring this provider in the provider definition itself, e.g.:

```
provider "dynatrace" {
  dt_env_url = data.key_vault_secret.dynatrace_url.value
  dt_api_token = data.key_vault_secret.dynatrace_token.value
}
```

We think this is generally secure, we're not committing plain-text secrets to source control and the values are kept in secure key vaults. This is ideal for us as we prefer to use data references to secrets rather than environment variables. 

In the [provider documentation](https://registry.terraform.io/providers/dynatrace-oss/dynatrace/latest/docs), there is no longer any mention of this method of configuring the provider. Is that because this method will be deprecated soon? I looked through the provider source and it still works, tested on v1.68.1 fine. We don't want to commit to using this method of provider configuration if it will be deprecated soon - so any info appreciated. 

Thanks

**Comment by kishikawa12** [comment]
Hi @MohammedZia-IPO,

Thanks for reaching out and apologies for the confusion. In order to streamline our documentation and prevent users that are not as familiar with Terraform to put sensitive values in plain-text, we decided to remove this section from the docs.

We won't be deprecating that option as we know that it's currently being used by multiple customers. We'll also reconsider internally how we can structure the documentation to note that this option is still possible but not cause confusion to new users.

Hope that helps!
