### ISSUE TITLE
"dynatrace_application_detection_rule_v2" should create new rule every time and not override

### ISSUE THREAD

**Issue by Vijayalakshmi-Yolbhavi** [dynatrace-oss/terraform-provider-dynatrace#575]
Hi Team,
I'm using resource `dynatrace_application_detection_rule_v2` for creating multiple rules for an application. Please note that we are managing state file. So, when we try creating multiple rules for same application, the existing rule is getting updated. 
We are looking to create new rule each time and doesn't want to override the existing rule. 

Could you please assist with this requirement?

Below is code snippet.
```hcl
------------------------------------------------------------------------------------------------
data "dynatrace_application" "existing_app_ids" {
  for_each = var.create_new_application ? {} : { for idx, rule in var.application_detection_rules : idx => rule ... }

  name = var.application_detection_rules[each.key].application_name
}

output "existing_app_ids" {
  value = { for idx, rule in var.application_detection_rules : idx => data.dynatrace_application.existing_app_ids[idx].id }
}

resource "dynatrace_application_detection_rule_v2" "apprule" {
  for_each = var.create_new_application ? {} : { for idx, rule in var.application_detection_rules : idx => rule }

  application_id = data.dynatrace_application.existing_app_ids[each.key].id
  matcher        = each.value.matcher
  pattern        = each.value.pattern
  lifecycle {
    prevent_destroy = true
    ignore_changes = [matcher, pattern]
  }
}
-------------------------------------------------------------------------------------
```

Thanks,
Vijayalakshmi

**Comment by Reinhard-Pilz-Dynatrace** [comment]
Hello @Vijayalakshmi-Yolbhavi 

Do you have an example for how the value of `application_detection_rules` would look like? I'm having troubles utilizing your code otherwise.

**Comment by Vijayalakshmi-Yolbhavi** [comment]
Hi @Reinhard-Pilz-Dynatrace,

Thanks for your response!
Please find the .tfvars files:

-------------------------------------------------------------------------------------------------------
create_new_application = false
application_detection_rules = [ {
  application_name = "test_automation"
  pattern = "test.com"
  matcher = "DOMAIN_MATCHES"
},
{
application_name = "test_automation"
pattern = "automation5"
matcher = "URL_CONTAINS"
}
]
-----------------------------------------------------------------------------------------------

Please note that "test_automation" is an exsiting application and we want to create multiple rules for this application by managing state file.

Let me know for any more details required.

Thanks,
Vijayalakshmi

**Comment by Reinhard-Pilz-Dynatrace** [comment]
Hi @Vijayalakshmi-Yolbhavi 

I need to assume a few things here, and just can hope I understood correctly what you're trying to do.

This code snippet here
```hcl
lifecycle {
    prevent_destroy = true
    ignore_changes = [matcher, pattern]
}
```
and your statement, that you always like to **add** but never **replace** tells me, that you're planning to run `terraform apply` on this piece of code subsequently with various different values for `application_detection_rules`. And whatever rules have already been configured for the applications should not get removed anymore. You just want to introduce new rules.

If I'm not mistaken, your issue is that you're indexing the resources by index

```hcl
resource "dynatrace_application_detection_rule_v2" "apprule" {
  for_each = var.create_new_application ? {} : { for idx, rule in var.application_detection_rules : idx => rule }
  ...
}
```
... with `idx` being the index of the configured `application_detection_rules`.

Terraform therefore maintains the instances of `dynatrace_application_detection_rule_v2` as `dynatrace_application_detection_rule_v2[0]`. `dynatrace_application_detection_rule_v2[1]`. ...

During subsequent invocations of `terraform apply` it's therefore unavoidable, that Terraform wants to update e.g. `dynatrace_application_detection_rule_v2[0]` instead of introducing a new instance. As far as Terraform is concerned, this is the same instance.

In order to avoid that behavior this approach could be helpful:

The data source `existing_app_ids` should get indexed by `application_name`. All you want to get from it later is the `ID` of the application anyways, like with `data.dynatrace_application.existing_app_ids[<name>].id`.

```hcl
data "dynatrace_application" "existing_app_ids" {
  for_each = var.create_new_application ? {} : { for idx, rule in var.application_detection_rules : rule.application_name => rule... }

  # application_name
  name = each.key
}
```

The resource `dynatrace_application_detection_rule_v2` needs to provide a unique index for every combination of `application_name`, `pattern` and `matcher`. The `idx` you were using until now is not really unique / does not reflect the rule you're trying to apply with that instance.

I would suggest to use `sha256(jsonencode(rule))` instead here. It ensures, that any configured `application_detection_rules` produces a unique index based on the contents.
If you are worried about checksum collisions, you could also opt for `join(":", [rule.application_name, rule.pattern, rule.matcher])`.

```hcl
resource "dynatrace_application_detection_rule_v2" "apprule" {
  for_each = var.create_new_application ? {} : { for idx, rule in var.application_detection_rules : sha256(jsonencode(rule)) => rule }

  application_id = data.dynatrace_application.existing_app_ids[each.value.application_name].id
  matcher        = each.value.matcher
  pattern        = each.value.pattern
  lifecycle {
    prevent_destroy = true
    #   ignore_changes  = [matcher, pattern]
  }
}
```
I believe, you won't even have to use the `ignore_changes` attribute within the `lifecycle` block anymore. 

When executing with the code above, this is what the output looks like in a local test

```
# dynatrace_application_detection_rule_v2.apprule["2dd4c7b8e474713d7d6b40e98335ca367bd6ec771149049632464810159df357"] will be created
  + resource "dynatrace_application_detection_rule_v2" "apprule" {
      + application_id = "APPLICATION-811CB0BD4714FF1F"
      + id             = (known after apply)
      + insert_after   = (known after apply)
      + matcher        = "URL_CONTAINS"
      + pattern        = "gitlab.local.home"
    }

  # dynatrace_application_detection_rule_v2.apprule["cd002fa73e41ca7527e75044bb4b045f32dd246616d1dc9ce62820969b039d9c"] will be created
  + resource "dynatrace_application_detection_rule_v2" "apprule" {
      + application_id = "APPLICATION-7A72BEF2D4C193DF"
      + id             = (known after apply)
      + insert_after   = (known after apply)
      + matcher        = "URL_CONTAINS"
      + pattern        = "jenkins.local.home"
    }
```

As you can see the instances of `dynatrace_application_detection_rule_v2` are now index with these checksums. Any additional entries within the list of `application_detection_rules` would produce a different checksum. Therefore you shouldn't have to worry about overrides.

Let me know if that helps,
Reinhard
