### ISSUE TITLE
Provider produced inconsistent result after apply

### ISSUE THREAD

**Issue by adhaferat** [dynatrace-oss/terraform-provider-dynatrace#605]
**Describe the bug**
I'm using dynatrace terraform provider to deploy on our instance with the version: v1.70.0. I'm getting this error when I do a terraform apply via a jenkins job:
```
17:22:13  │ Error: Revisions: '
17:22:13  │  'f3b9d050-ae37-11ef-8001-010000000007' for Key 'df006d71-d691-3b17-ba92-badc2da16b6e'' for 'builtin:anomaly-detection.services' are outdated
17:22:13  │ 
17:22:13  │ Error: Provider produced inconsistent result after apply
17:22:13  │ 
17:22:13  │ When applying changes to
17:22:13  │ module.default_anomaly_detections.dynatrace_service_anomalies_v2.default_services_anomalies,
17:22:13  │ provider "provider[\"registry.terraform.io/dynatrace-oss/dynatrace\"]"
17:22:13  │ produced an unexpected new value: Root resource was present, but now
17:22:13  │ absent.
17:22:13  │ 
17:22:13  │ This is a bug in the provider, which should be reported in the provider's
17:22:13  │ own issue tracker. 
```

To Reproduce the issue
Terraform apply on our project.

Expected behavior
Consistent behaviour between terraform applies.

**Comment by Reinhard-Pilz-Dynatrace** [comment]
Hello @adhaferat 

I'm curious. Are you getting that error consistently or was that a one-off?

I'm asking, because based on the error message it looks like someone else (somebody using the WebUI or another automation component) has made changes to that record at exactly the same time than Terraform. That raised a conflict and our provider wasn't able to react properly to that. We can look into introducing functionality that catches that specific error in one of our next releases.

If you're getting that error permanently, then something else must be going on.

thanks,
Reinhard

**Comment by adhaferat** [comment]
Hello,
It happened once of twice on multiple landscapes at the same time during a batch deployment. I think there was not someone using the WebUI, but maybe a network issue then.. 
I am not getting the issue anymore, thank you for you answer !
