### ISSUE TITLE
This is a bug in the provider

### ISSUE THREAD

**Issue by Tony-WangQAQ** [dynatrace-oss/terraform-provider-dynatrace#612]
**Describe the bug**
When I configure dynatrace problem notification through terraform, the headers parameter is abnormal. This is very strange. The same configuration is normal when it is created for the first time. However, when I change some configurations (such as changing the configuration status to true) and re-run the code, this problem occurs, as shown in the attachment.

**Expected behavior**
The official description of dynatrace_webhook_notification configuration is as follows, "secret_value and value are mutually exclusive. Only one of those two is allowed to be specified." However, this bug seems to require both values ​​to be specified when reading the module, which is not a reasonable place.

**Screenshots**
![截屏2024-12-10 09 24 15](https://github.com/user-attachments/assets/709c2e6b-54bf-45e5-8599-4a2b9f6439d7)

**Desktop (please complete the following information):**
 - OS: [ubuntu]
 - Browser [chrome]
 - Version [22.04]

**Comment by Reinhard-Pilz-Dynatrace** [comment]
Hello @Tony-WangQAQ 

Would you be able to provide the HCL code for the `dynatrace_webhook_notification` you're using here?
I've tried to reproduce with a couple of samples, but so far wasn't able to get the results you're seeing.

thanks,
Reinhard

**Comment by Tony-WangQAQ** [comment]
Hello @Reinhard-Pilz-Dynatrace 
Thanks a lot
Because there is some sensitive information in the current test code, I need to modify it. If the modification is completed, I will update it to you.
Thanks,
Tony

**Comment by Reinhard-Pilz-Dynatrace** [comment]
Hi Tony,

I unfortunately still cannot reproduce that error message. But based on the wording in that error I have a hunch that it has something to do with this [bug](https://github.com/hashicorp/terraform-plugin-sdk/issues/652) in the Terraform Plugin SDK. We have to circumvent that phenomenon in several resources. And that bit of information

```
cty.ObjectVal(map[string]cty.Value{"name":cty.NullVal(cty.String), "secret_value":cty.StringVal(""), "value":cty.NullVal(cty.String)})
```

makes me believe, that it might be the root cause.

Right now we don't have a proper way to handle this case. But with the release of the provider scheduled for tomorrow I have added something that hopefully allows you to avoid the error:

When running `terraform apply` or `terraform plan`, you need to set the environment variable `DYNATRACE_FORCE_NEW_ON_HEADERS` to `true`. In that case the provider will enforce that any changes within the headers require Terraform to recreate the whole resource.

I've hidden that feature behind an environment variable for the moment, so we can collect feedback from you first. If it is indeed a solution we will make that default behavior in the future.

Let me know once you were able to try this out with the upcoming release of the provider. I will keep this ticket open until then.

**Comment by Tony-WangQAQ** [comment]
Hello @Reinhard-Pilz-Dynatrace 
Thanks very mush.
Currently I am ignoring the Header content by adding the following code.
```
lifecycle {
    ignore_changes = [
      headers
    ]
  }
```
Because I have other work to complete urgently, if I have enough time, I will test and verify it and feedback the results to you

Thanks a lot，
Tony
