### ISSUE TITLE
[Enhancement] add "Key Requests"

### ISSUE THREAD

**Issue by kannanbalaji** [dynatrace-oss/terraform-provider-dynatrace#68]
Hi Team,

Please add "Key Requests".

As a customer, we have multiple services and we create custom alerts, dashboards, SLI/SLO based on the key requests.

We are looking for an option to "Mark a request as key request".

Regards,

Balaji

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello @kannanbalaji ,

At the moment there doesn't exist an REST Endpoint within the Dynatrace Configuration API for Key Requests. It is expected to be available by the end of November 2021.
I will keep that ticket open until then - as soon as Key Requests are configurable via REST, I'll add the necessary resource to the Terraform Provider.

**Comment by kannanbalaji** [comment]
Hi Reinhard-Pilz,
Happy New Year!

Any update on this ticket?

**Comment by kannanbalaji** [comment]
Hi Reinhard-Pilz,

Any update on this ticket?
In your last comment, it was expected to be available last year Nov 2021.
We are looking forward to this feature.

Appreciate your time.

Regards,
Balaji Kannan

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello Kannan,

Sorry for the delay here.
Key Requests are meanwhile indeed available via Settings 2.0 REST API. I will schedule in support for them with the upcoming release. Currently internal tasks require me to focus on a few other things primarily, that's why pushing out new releases for this project is quite delayed at the moment.

**Comment by kannanbalaji** [comment]
Hi Reinhard-Pilz,

Thank you, for the update!
Can you please give me specific data on when this will be available in terraform?
We are actively creating kits for dynatrace, your information will help prioritize our work.

Appreciate your time.

Regards,
Balaji Kannan

**Comment by kannanbalaji** [comment]
Hi Reinhard-Pilz,

Please check the above question.

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Sorry @kannanbalaji , I missed that question.
I will schedule in Key Requests for the next release of the Terraform Provider. Because preparations for [Perform](https://www.dynatrace.com/perform-2022/) are at the moment eating up most of my time, I need to ask for patience until the week of February 14th for that.

**Comment by kannanbalaji** [comment]
Hi Reinhard-Pilz,

A gentle reminder on this work.
Do keep me posted with the release plan.  
Appreciate your time.

Regards,
Balaji Kannan

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello @kannanbalaji ,

Good news, the resource `dynatrace_key_requests` is supported since [v1.10.0](https://github.com/dynatrace-oss/terraform-provider-dynatrace/releases/tag/v1.10.0) which was released last Friday. 

thanks for the reminder - I completely forgot about closing the enhancement tickets for the new features.

**Comment by kannanbalaji** [comment]
Hi Reinhard-Pilz,

Thank you, for the update.
I can see the resources here: https://registry.terraform.io/providers/dynatrace-oss/dynatrace/latest/docs/resources/key_requests

When I try to export, I get this msg: **Unknown resource `dynatrace_key_requests**

`./terraform-provider-dynatrace_v1.10.0 export dynatrace_key_requests
`**Unknown resource `dynatrace_key_requests`**

I did use the latest version to export "terraform-provider-dynatrace_v1.10.0"

Please take a look.

Regards,
Balaji Kannan

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hi @kannanbalaji 
You're right, the export functionality is not yet there for that resource. I'm planning to ship it with the upcoming release, hoping to make it by the end of this week.

**Comment by kannanbalaji** [comment]
Thank you @Dynatrace-Reinhard-Pilz

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hi @kannanbalaji , sorry for the delay. You can expect the next release on Friday this week.

**Comment by kannanbalaji** [comment]
Hi @Dynatrace-Reinhard-Pilz 

I am still getting this msg when I try to export - **### Unknown resource `dynatrace_key_requests**

./terraform-provider-dynatrace_v1.11.0 export dynatrace_key_requests
Unknown resource `dynatrace_key_requests`

Please let me know.

Regards,
Balaji Kannan

**Comment by kannanbalaji** [comment]
Any update on this?
