### ISSUE TITLE
Importing dynatrace resources

### ISSUE THREAD

**Issue by Hari-viswadeep** [dynatrace-oss/terraform-provider-dynatrace#74]
Couldn't find details about importing existing dynatrace resources.

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello @Hari-viswadeep 

As with any resource available via a terraform provider you can use the `terraform import` functionality as explaned [here[(https://learn.hashicorp.com/tutorials/terraform/state-import?in=terraform/state&utm_source=WEBSITE&utm_medium=WEB_IO&utm_offer=ARTICLE_PAGE&utm_content=DOCS).

Because that way of importing resources can be pretty tedious, we decided to offer something more convenient in addition to that. Please take a look a the [README](https://github.com/dynatrace-oss/terraform-provider-dynatrace#usage-examples) of this repository. It contains examples for how to use `terraform-provider-dynatrace export`.

**Comment by VatslauX** [comment]
We need it reopen and make as standard import into the state.
Becasue dynatrce is not AWS config. It is Expected 90% of changes from users in UI.
and 10% admin chnages from terrraform only.
That mean key feature is to handle like a GIT incoming changes from all directions - regardless who did this "commit".
As admin - we need to able accept/merge new state or restore master state on daily basis without any triks

That mean
terraform-provider-dynatrace import 
command is needed to fetch remote chnages into state
