### ISSUE TITLE
dynatrace_custom_anomalies updates on subsequent runs

### ISSUE THREAD

**Issue by JosephHobbs** [dynatrace-oss/terraform-provider-dynatrace#79]
I defined some dynatrace_custom_anomalies resources within a project.  As part of the resource I did NOT set disabled_reason or warning_reason.  On subsequent runs, terraform see's these fields set to NONE and wants to update them to null.

![image](https://user-images.githubusercontent.com/43007348/134790813-d217c769-0891-4423-bd9c-b86e53de3883.png)

I'm under the impression that these values are really set on the Dynatrace side and not so much the client side.  If that's the case, should these not be detected as differences?

I'm going to ignore them via lifecycle at this point.  I could probably just set them to NONE and that would be fine too.  Just not sure the 'best' answer here.

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hi Joseph,

I remember, when implementing that resource, whether to treat `NONE` the same as `not specified`. Reasoning behind that is, that the both enumerations explicitly offer the `NONE` value as one of the options - hinting that, although CURRENTLY being used as the default value, that semantics could change in the future.

I can see two possible improvements here:
a) Declare `disabled_reason` and `warning_reason` as `required`, and therefore force everyone to at least set `NONE`
b) Assume `NONE` to be identical with `not specified`

Since you're the first user who stumbled across this, your opinion matters - I'm really ok with either solution, effort for implementation is not worth mentioning.

Your thoughts?

**Comment by JosephHobbs** [comment]
From what I understand from the documentation on these fields, these fields are intended to be written to by Dynatrace and not the client.  So it would contain a reason as to why a specific anomaly detection is in warning or has been disabled by Dynatrace.  For this reason, it's not something I would expect to define in my resource on the Terraform side.

One point that supports this theory is the fact that these parameters are present in the documentation for reading (https://www.dynatrace.com/support/help/dynatrace-api/configuration-api/anomaly-detection-api/anomaly-detection-api-metric-events/get-event/) but not documented on the creating side (https://www.dynatrace.com/support/help/dynatrace-api/configuration-api/anomaly-detection-api/anomaly-detection-api-metric-events/post-event/).

![image](https://user-images.githubusercontent.com/43007348/135323315-39a83cfc-1487-408b-a1a6-b5f9363356d6.png)

If my assumptions above are correct, I'd just drop/ignore then from the resource definition entirely.
