### ISSUE TITLE
bug: synthetic_monitors: moving from enabled=false to enabled=true is buggy

### ISSUE THREAD

**Issue by aslafy-z** [dynatrace-oss/terraform-provider-dynatrace#88]
When changing enabled=false to enabled=true in my already existing state, only the first synthetic monitor is getting updated.
The other way around works as expected.

My current workaround is to `terraform destroy` then `terraform apply`

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello @aslafy-z 

There was indeed an issue with the handling of boolean properties within `dynatrace_browser_monitor` and `dynatrace_http_monitor`. I've now taken care of that apparent bug within the code.

I've however identified yet another problem, that's why I'm keeping this issue open. Configuring Synthetic Monitors via REST API is unfortunately a lazy operation. In other words, immediately after any changes are getting sent (CREATE, UPDATE), not all Nodes of the Dynatrace Server are aware of it. It can take several seconds until all Server Nodes are in sync about that change.
This means, that depending on what Cluster Node is serving a subsequent READ operation, you're either getting the old status or the new status delivered back.
This issue already exists when creating new Monitors, but for that case the provider already takes care of things. You may have noticed that it sometimes takes quite a while until the resources have been created.
The same issue can occur when sending an UPDATE (e.g. changing the `enabled` property). After `terraform apply` a subsequent `terraform plan` is likely going to complain that the `enabled` flag is still to be updated. That behavior changes after a few seconds (once ALL server nodes are aware of the change).

Can you confirm, that v1.8.4 also in your case changes the `enabled` property as expected now (with the delays I've explained factored in)?

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Please re-open this issue in case the behavior doesn't reflect what I explained above.
